### ISSUE TITLE
media cannot be played by this device

### ISSUE THREAD

**Issue by CleverMod** [jellyfin/jellyfin-android#1046]
### Describe the bug

2.5.0 External mxplayer player throws this prompt when playing some videos
2.4.4 Can be played without any issues

### Application version

2.5.0

### Where did you install the app from?

None

### Device information

Xiaomi 10S

### Android version

11

### Jellyfin server version

10.8.10

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [x] External player (VLC, mpv, MX Player)

**Comment by Elyorn** [comment]
Having the same issue, but with MPV, on two different decices. One is a poco f3 running arrowos rom (android 13), the other one is a tab s6 running android 12. Both work fine with on 2.4.4

**Comment by Elyorn** [comment]
> This issue is fixed in the next update (2.5.2).

That was fast. Thanks for all your work, as well as the team's!

**Comment by theuserwhoisnotadeveloper** [comment]
The bug still happens on version 2.6.2 using mpv 2024-11-16 or vlc

**Comment by FadedMaster** [comment]
> The bug still happens on version 2.6.2 using mpv 2024-11-16 or vlc

Same here on 2.6.3.

**Comment by Miminepho** [comment]
Also experiencing the same issue on 2.6.3 with both VLC and mpv.

Here's the logcat:

```
09-26 14:22:07.639  1032  1032 E MediaSourceResolver: Cannot create JellyfinMediaSource
09-26 14:22:07.639  1032  1032 E MediaSourceResolver: java.lang.IllegalArgumentException: No play method found for {medianame} ({mediaid})
09-26 14:22:07.639  1032  1032 E MediaSourceResolver:   at org.jellyfin.mobile.player.source.JellyfinMediaSource.<init>(SourceFile:355)
09-26 14:22:07.639  1032  1032 E MediaSourceResolver:   at org.jellyfin.mobile.player.source.MediaSourceResolver.resolveMediaSource-tZkwj4A(SourceFile:441)
09-26 14:22:07.639  1032  1032 E MediaSourceResolver:   at org.jellyfin.mobile.player.source.MediaSourceResolver$resolveMediaSource$1.invokeSuspend(SourceFile:21)
09-26 14:22:07.639  1032  1032 E MediaSourceResolver:   at U4.a.resumeWith(SourceFile:9)
09-26 14:22:07.639  1032  1032 E MediaSourceResolver:   at n5.M.run(SourceFile:107)
09-26 14:22:07.639  1032  1032 E MediaSourceResolver:   at android.os.Handler.handleCallback(Handler.java:995)
09-26 14:22:07.639  1032  1032 E MediaSourceResolver:   at android.os.Handler.dispatchMessage(Handler.java:103)
09-26 14:22:07.639  1032  1032 E MediaSourceResolver:   at android.os.Looper.loopOnce(Looper.java:248)
09-26 14:22:07.639  1032  1032 E MediaSourceResolver:   at android.os.Looper.loop(Looper.java:338)
09-26 14:22:07.639  1032  1032 E MediaSourceResolver:   at android.app.ActivityThread.main(ActivityThread.java:9106)
09-26 14:22:07.639  1032  1032 E MediaSourceResolver:   at java.lang.reflect.Method.invoke(Native Method)
09-26 14:22:07.639  1032  1032 E MediaSourceResolver:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
09-26 14:22:07.639  1032  1032 E MediaSourceResolver:   at com.android.internal.os.ExecInit.main(ExecInit.java:50)
09-26 14:22:07.639  1032  1032 E MediaSourceResolver:   at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
09-26 14:22:07.639  1032  1032 E MediaSourceResolver:   at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
```
