### ISSUE TITLE
Aplication stuck in Landscape

### ISSUE THREAD

**Issue by jkalousek** [jellyfin/jellyfin-android#1117]
### Describe the bug

1. Open app
2. App only shows in landscape and I was not able to figure out a way to get it into portrait (all other apps are ok, auto rotate enabled)
3. This results in inability to sign in as either code or input fields are out of screen

![Screenshot_20230626-075116](https://github.com/jellyfin/jellyfin-android/assets/8996764/4e77b187-876a-4ed9-9234-a24eb8463e8a)

### Logs

```shell
2023-06-26 07:50:58.825  1456-3919  ActivityTaskManager     system_server                        I  START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.jellyfin.androidtv/.ui.startup.StartupActivity bnds=[641,1604][836,1826]} from uid 10104
2023-06-26 07:50:58.885  1456-3919  CoreBackPreview         system_server                        D  Window{d027a56 u0 Splash Screen org.jellyfin.androidtv}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@5035430, mPriority=0}
2023-06-26 07:50:58.893  1456-1569  ActivityManager         system_server                        I  Start proc 14958:org.jellyfin.androidtv/u0a207 for next-top-activity {org.jellyfin.androidtv/org.jellyfin.androidtv.ui.startup.StartupActivity}
2023-06-26 07:50:58.898 14958-14958 Zygote                  pid-14958                            W  Can't access app profile directory: /data_mirror/cur_profiles/0/org.jellyfin.androidtv
2023-06-26 07:50:58.974 14958-14958 lyfin.androidtv         pid-14958                            W  type=1400 audit(0.0:40024): avc: denied { read } for name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=387 scontext=u:r:untrusted_app:s0:c207,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=org.jellyfin.androidtv
2023-06-26 07:50:58.978 14958-14958 lyfin.androidtv         pid-14958                            W  type=1400 audit(0.0:40025): avc: denied { read } for name="u:object_r:odsign_prop:s0" dev="tmpfs" ino=320 scontext=u:r:untrusted_app:s0:c207,c256,c512,c768 tcontext=u:object_r:odsign_prop:s0 tclass=file permissive=0 app=org.jellyfin.androidtv
2023-06-26 07:50:58.978 14958-14958 lyfin.androidtv         pid-14958                            W  type=1400 audit(0.0:40026): avc: denied { read } for name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=387 scontext=u:r:untrusted_app:s0:c207,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=org.jellyfin.androidtv
2023-06-26 07:50:58.983 14958-14958 org.jellyfin.androidtv  pid-14958                            W  ART APEX data files are untrusted.
2023-06-26 07:50:58.982 14958-14958 lyfin.androidtv         pid-14958                            W  type=1400 audit(0.0:40027): avc: denied { getattr } for path="/apex/apex-info-list.xml" dev="tmpfs" ino=67 scontext=u:r:untrusted_app:s0:c207,c256,c512,c768 tcontext=u:object_r:apex_info_file:s0 tclass=file permissive=0 app=org.jellyfin.androidtv
2023-06-26 07:50:58.986 14958-14958 lyfin.androidtv         pid-14958                            W  type=1400 audit(0.0:40028): avc: denied { lock } for path="/system/framework/arm64/boot.art" dev="dm-24" ino=1407 scontext=u:r:untrusted_app:s0:c207,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=org.jellyfin.androidtv
2023-06-26 07:50:59.071 14958-14958 org.jellyfin.androidtv  pid-14958                            D  Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
2023-06-26 07:50:59.071 14958-14958 org.jellyfin.androidtv  pid-14958                            D  I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt70l.dat
2023-06-26 07:50:59.109 14958-14958 org.jellyfin.androidtv  pid-14958                            E  Unable to find pattern file or unable to map it for am
2023-06-26 07:50:59.273 14958-14958 ziparchive              pid-14958                            W  Unable to open '/data/app/~~hFIsQIec4N4abfdLnmhS7g==/org.jellyfin.androidtv-cNUAoJpwV5cccOS73GyNPw==/split_config.arm64_v8a.dm': No such file or directory
2023-06-26 07:50:59.273 14958-14958 ziparchive              pid-14958                            W  Unable to open '/data/app/~~hFIsQIec4N4abfdLnmhS7g==/org.jellyfin.androidtv-cNUAoJpwV5cccOS73GyNPw==/split_config.arm64_v8a.dm': No such file or directory
2023-06-26 07:50:59.273 14958-14958 org.jellyfin.androidtv  pid-14958                            W  Entry not found
2023-06-26 07:50:59.274 14958-14958 ziparchive              pid-14958                            W  Unable to open '/data/app/~~hFIsQIec4N4abfdLnmhS7g==/org.jellyfin.androidtv-cNUAoJpwV5cccOS73GyNPw==/split_config.cs.dm': No such file or directory
2023-06-26 07:50:59.274 14958-14958 ziparchive              pid-14958                            W  Unable to open '/data/app/~~hFIsQIec4N4abfdLnmhS7g==/org.jellyfin.androidtv-cNUAoJpwV5cccOS73GyNPw==/split_config.cs.dm': No such file or directory
2023-06-26 07:50:59.274 14958-14958 org.jellyfin.androidtv  pid-14958                            W  Entry not found
2023-06-26 07:50:59.275 14958-14958 ziparchive              pid-14958                            W  Unable to open '/data/app/~~hFIsQIec4N4abfdLnmhS7g==/org.jellyfin.androidtv-cNUAoJpwV5cccOS73GyNPw==/split_config.xxhdpi.dm': No such file or directory
2023-06-26 07:50:59.275 14958-14958 ziparchive              pid-14958                            W  Unable to open '/data/app/~~hFIsQIec4N4abfdLnmhS7g==/org.jellyfin.androidtv-cNUAoJpwV5cccOS73GyNPw==/split_config.xxhdpi.dm': No such file or directory
2023-06-26 07:50:59.275 14958-14958 org.jellyfin.androidtv  pid-14958                            W  Entry not found
2023-06-26 07:50:59.307 14958-14958 GraphicsEnvironment     org.jellyfin.androidtv               V  ANGLE Developer option for 'org.jellyfin.androidtv' set to: 'default'
2023-06-26 07:50:59.307 14958-14958 GraphicsEnvironment     org.jellyfin.androidtv               V  ANGLE GameManagerService for org.jellyfin.androidtv: false
2023-06-26 07:50:59.317 14958-14958 ACRA                    org.jellyfin.androidtv               D  ACRA processName='org.jellyfin.androidtv'
2023-06-26 07:50:59.318 14958-14958 ACRA                    org.jellyfin.androidtv               I  ACRA is enabled for org.jellyfin.androidtv, initializing...
2023-06-26 07:50:59.402 14958-14958 DisplayPreferencesStore org.jellyfin.androidtv               E  Unable to retrieve displaypreferences. (displayPreferencesId=livetv, app=jellyfin-androidtv)
                                                                                                    org.jellyfin.sdk.api.client.exception.MissingUserIdException: Required value userId is null. Provide it by setting ApiClient.userId or passing it in the function call.
                                                                                                    	at org.jellyfin.sdk.api.operations.DisplayPreferencesApi.getDisplayPreferences$default(DisplayPreferencesApi.kt:32)
                                                                                                    	at org.jellyfin.androidtv.preference.store.DisplayPreferencesStore.update$suspendImpl(DisplayPreferencesStore.kt:59)
                                                                                                    	at org.jellyfin.androidtv.preference.store.DisplayPreferencesStore.update(Unknown Source:0)
                                                                                                    	at org.jellyfin.androidtv.preference.PreferencesRepository.onSessionChanged(PreferencesRepository.kt:31)
                                                                                                    	at org.jellyfin.androidtv.auth.repository.SessionRepositoryImpl.setCurrentSession(SessionRepository.kt:152)
                                                                                                    	at org.jellyfin.androidtv.auth.repository.SessionRepositoryImpl.restoreSession(SessionRepository.kt:74)
                                                                                                    	at org.jellyfin.androidtv.SessionInitializer$create$1.invokeSuspend(SessionInitializer.kt:21)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
                                                                                                    	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                                                                                                    	at org.jellyfin.androidtv.SessionInitializer.create(SessionInitializer.kt:20)
                                                                                                    	at org.jellyfin.androidtv.SessionInitializer.create(SessionInitializer.kt:12)
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7527)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7038)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6809)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2140)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7937)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
                                                                                                    	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
2023-06-26 07:50:59.403 14958-14958 DisplayPreferencesStore org.jellyfin.androidtv               E  Unable to retrieve displaypreferences. (displayPreferencesId=usersettings, app=emby)
                                                                                                    org.jellyfin.sdk.api.client.exception.MissingUserIdException: Required value userId is null. Provide it by setting ApiClient.userId or passing it in the function call.
                                                                                                    	at org.jellyfin.sdk.api.operations.DisplayPreferencesApi.getDisplayPreferences$default(DisplayPreferencesApi.kt:32)
                                                                                                    	at org.jellyfin.androidtv.preference.store.DisplayPreferencesStore.update$suspendImpl(DisplayPreferencesStore.kt:59)
                                                                                                    	at org.jellyfin.androidtv.preference.store.DisplayPreferencesStore.update(Unknown Source:0)
                                                                                                    	at org.jellyfin.androidtv.preference.PreferencesRepository.onSessionChanged(PreferencesRepository.kt:32)
                                                                                                    	at org.jellyfin.androidtv.auth.repository.SessionRepositoryImpl.setCurrentSession(SessionRepository.kt:152)
                                                                                                    	at org.jellyfin.androidtv.auth.repository.SessionRepositoryImpl.restoreSession(SessionRepository.kt:74)
                                                                                                    	at org.jellyfin.androidtv.SessionInitializer$create$1.invokeSuspend(SessionInitializer.kt:21)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
                                                                                                    	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                                                                                                    	at org.jellyfin.androidtv.SessionInitializer.create(SessionInitializer.kt:20)
                                                                                                    	at org.jellyfin.androidtv.SessionInitializer.create(SessionInitializer.kt:12)
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7527)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7038)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6809)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2140)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7937)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
                                                                                                    	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
2023-06-26 07:50:59.406 14958-14958 ACRA                    org.jellyfin.androidtv               D  ACRA processName='org.jellyfin.androidtv'
2023-06-26 07:50:59.451 14958-14958 ACRA                    org.jellyfin.androidtv               D  onActivityCreated class org.jellyfin.androidtv.ui.startup.StartupActivity
2023-06-26 07:50:59.480 14958-14958 ACRA                    org.jellyfin.androidtv               D  onActivityStarted class org.jellyfin.androidtv.ui.startup.StartupActivity
2023-06-26 07:50:59.495 14958-14958 DisplayPreferencesStore org.jellyfin.androidtv               E  Unable to retrieve displaypreferences. (displayPreferencesId=livetv, app=jellyfin-androidtv)
                                                                                                    org.jellyfin.sdk.api.client.exception.MissingUserIdException: Required value userId is null. Provide it by setting ApiClient.userId or passing it in the function call.
                                                                                                    	at org.jellyfin.sdk.api.operations.DisplayPreferencesApi.getDisplayPreferences$default(DisplayPreferencesApi.kt:32)
                                                                                                    	at org.jellyfin.androidtv.preference.store.DisplayPreferencesStore.update$suspendImpl(DisplayPreferencesStore.kt:59)
                                                                                                    	at org.jellyfin.androidtv.preference.store.DisplayPreferencesStore.update(Unknown Source:0)
                                                                                                    	at org.jellyfin.androidtv.preference.PreferencesRepository.onSessionChanged(PreferencesRepository.kt:31)
                                                                                                    	at org.jellyfin.androidtv.auth.repository.SessionRepositoryImpl.setCurrentSession(SessionRepository.kt:152)
                                                                                                    	at org.jellyfin.androidtv.auth.repository.SessionRepositoryImpl.restoreSession(SessionRepository.kt:74)
                                                                                                    	at org.jellyfin.androidtv.ProcessLifecycleInitializer$create$1$onStart$1.invokeSuspend(ProcessLifecycleInitializer.kt:43)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
                                                                                                    	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                                                                                                    	at org.jellyfin.androidtv.ProcessLifecycleInitializer$create$1.onStart(ProcessLifecycleInitializer.kt:42)
                                                                                                    	at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:39)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:271)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:313)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:151)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
                                                                                                    	at androidx.lifecycle.ProcessLifecycleOwner.activityStarted(ProcessLifecycleOwner.java:113)
                                                                                                    	at androidx.lifecycle.ProcessLifecycleOwner$3$1.onActivityPostStarted(ProcessLifecycleOwner.java:179)
                                                                                                    	at android.app.Activity.dispatchActivityPostStarted(Activity.java:1427)
                                                                                                    	at android.app.Activity.performStart(Activity.java:8451)
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3677)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:204)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2314)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7937)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
                                                                                                    	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
2023-06-26 07:50:59.495 14958-14958 DisplayPreferencesStore org.jellyfin.androidtv               E  Unable to retrieve displaypreferences. (displayPreferencesId=usersettings, app=emby)
                                                                                                    org.jellyfin.sdk.api.client.exception.MissingUserIdException: Required value userId is null. Provide it by setting ApiClient.userId or passing it in the function call.
                                                                                                    	at org.jellyfin.sdk.api.operations.DisplayPreferencesApi.getDisplayPreferences$default(DisplayPreferencesApi.kt:32)
                                                                                                    	at org.jellyfin.androidtv.preference.store.DisplayPreferencesStore.update$suspendImpl(DisplayPreferencesStore.kt:59)
                                                                                                    	at org.jellyfin.androidtv.preference.store.DisplayPreferencesStore.update(Unknown Source:0)
                                                                                                    	at org.jellyfin.androidtv.preference.PreferencesRepository.onSessionChanged(PreferencesRepository.kt:32)
                                                                                                    	at org.jellyfin.androidtv.auth.repository.SessionRepositoryImpl.setCurrentSession(SessionRepository.kt:152)
                                                                                                    	at org.jellyfin.androidtv.auth.repository.SessionRepositoryImpl.restoreSession(SessionRepository.kt:74)
                                                                                                    	at org.jellyfin.androidtv.ProcessLifecycleInitializer$create$1$onStart$1.invokeSuspend(ProcessLifecycleInitializer.kt:43)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
                                                                                                    	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                                                                                                    	at org.jellyfin.androidtv.ProcessLifecycleInitializer$create$1.onStart(ProcessLifecycleInitializer.kt:42)
                                                                                                    	at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:39)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:271)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:313)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:151)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
                                                                                                    	at androidx.lifecycle.ProcessLifecycleOwner.activityStarted(ProcessLifecycleOwner.java:113)
                                                                                                    	at androidx.lifecycle.ProcessLifecycleOwner$3$1.onActivityPostStarted(ProcessLifecycleOwner.java:179)
                                                                                                    	at android.app.Activity.dispatchActivityPostStarted(Activity.java:1427)
                                                                                                    	at android.app.Activity.performStart(Activity.java:8451)
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3677)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:204)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2314)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7937)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
                                                                                                    	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
2023-06-26 07:50:59.496 14958-14958 ACRA                    org.jellyfin.androidtv               D  onActivityResumed class org.jellyfin.androidtv.ui.startup.StartupActivity
2023-06-26 07:50:59.580  1456-1508  CoreBackPreview         system_server                        D  Window{3011084 u0 org.jellyfin.androidtv/org.jellyfin.androidtv.ui.startup.StartupActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@ec344a2, mPriority=0}
2023-06-26 07:50:59.682  1456-1508  ConnectivityService     system_server                        D  requestNetwork for uid/pid:10207/14958 activeRequest: null callbackRequest: 1841 [NetworkRequest [ REQUEST id=1842, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10207 RequestorUid: 10207 RequestorPkg: org.jellyfin.androidtv UnderlyingNetworks: Null] ]] callback flags: 0 order: 2147483647
2023-06-26 07:50:59.695  1456-1553  ActivityTaskManager     system_server                        I  Displayed org.jellyfin.androidtv/.ui.startup.StartupActivity: +862ms
2023-06-26 07:50:59.701  1456-1907  WifiNetworkFactory      system_server                        D  got request NetworkRequest [ REQUEST id=1842, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10207 RequestorUid: 10207 RequestorPkg: org.jellyfin.androidtv UnderlyingNetworks: Null] ]
2023-06-26 07:50:59.701  1456-1907  UntrustedW...orkFactory system_server                        D  got request NetworkRequest [ REQUEST id=1842, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10207 RequestorUid: 10207 RequestorPkg: org.jellyfin.androidtv UnderlyingNetworks: Null] ]
2023-06-26 07:50:59.702  1456-1907  OemPaidWif...orkFactory system_server                        D  got request NetworkRequest [ REQUEST id=1842, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10207 RequestorUid: 10207 RequestorPkg: org.jellyfin.androidtv UnderlyingNetworks: Null] ]
2023-06-26 07:50:59.703  1456-1907  MultiInter...orkFactory system_server                        D  got request NetworkRequest [ REQUEST id=1842, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10207 RequestorUid: 10207 RequestorPkg: org.jellyfin.androidtv UnderlyingNetworks: Null] ]
2023-06-26 07:50:59.756 14958-15022 org.jellyf...rDiscovery org.jellyfin.androidtv               I  Starting discovery with timeout of 500ms
2023-06-26 07:50:59.759 14958-15022 org.jellyf...rDiscovery org.jellyfin.androidtv               D  Discovering via /255.255.255.255
2023-06-26 07:50:59.759 14958-15022 org.jellyf...rDiscovery org.jellyfin.androidtv               D  Finished sending broadcast, listening for responses
2023-06-26 07:50:59.759 14958-15022 org.jellyf...rDiscovery org.jellyfin.androidtv               D  Reading reply...
2023-06-26 07:51:00.055  1456-3919  CoreBackPreview         system_server                        D  Window{d027a56 u0 Splash Screen org.jellyfin.androidtv EXITING}: Setting back callback null
2023-06-26 07:51:00.056  1456-12553 InputManager-JNI        system_server                        W  Input channel object 'd027a56 Splash Screen org.jellyfin.androidtv (client)' was disposed without first being removed with the input manager!
2023-06-26 07:51:00.260 14958-15022 org.jellyf...rDiscovery org.jellyfin.androidtv               D  Reading reply...
2023-06-26 07:51:00.763 14958-15022 org.jellyf...rDiscovery org.jellyfin.androidtv               D  Reading reply...
2023-06-26 07:51:01.265 14958-15022 org.jellyf...rDiscovery org.jellyfin.androidtv               D  Reading reply...
2023-06-26 07:51:01.767 14958-15022 org.jellyf...rDiscovery org.jellyfin.androidtv               D  Reading reply...
2023-06-26 07:51:02.269 14958-15022 org.jellyf...rDiscovery org.jellyfin.androidtv               D  Reading reply...
2023-06-26 07:51:02.772 14958-15022 org.jellyf...rDiscovery org.jellyfin.androidtv               D  Reading reply...
2023-06-26 07:51:03.274 14958-15022 org.jellyf...rDiscovery org.jellyfin.androidtv               D  Reading reply...
2023-06-26 07:51:03.776 14958-15022 org.jellyf...rDiscovery org.jellyfin.androidtv               D  Reading reply...
```

### Application version

0.15.10

### Where did you install the app from?

Google Play

### Device information

Google Pixel 7

### Android version

Graphene OS (Android 13)

### Jellyfin server version

10.8.10

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
We have two apps for Android, one for televisions and one for other devices (phone/tablet etc.). You're using the TV app on a phone which is not supported.

**Comment by jkalousek** [comment]
Ok sorry I didn't notice. This was the first app that Google Play directly opened when I entered Jellyfin and on homescreen it also just shows "Jellyfin". Why is it even possible to install, shouldn't it be incompatible with mobile devices?

Once again sorry for my mistake but the distinction is practically non existent on my device except title under Play Store.

**Comment by nielsvanvelzen** [comment]
Unfortunately a lot of cheap Android TV boxes don't identify themself as a "TV" so restricting the app to TV only would cause issues for those devices.

We do have a warning that shows when you're using the app on the wrong device but that is after you sign in, which as you mention is not really possible on a phone.
