### ISSUE TITLE
can't forward in playback

### ISSUE THREAD

**Issue by fagervan** [jellyfin/jellyfin-android#133]
only can start playback video from start.
when I try to forward, the video stops.

server: jellyfin_10.3.1_windows-x64
client: android-beta9. (huawei gw)

Log in the server:
```
[08:39:43] [INF] Deleting partial stream file(s) C:\jellyfin\transcode\transcoding-temp\28abad54e8a5ed1ca03d7f36c7a9d83a.mkv
[08:39:43] [ERR] Error deleting partial stream file(s) C:\jellyfin\transcode\transcoding-temp\28abad54e8a5ed1ca03d7f36c7a9d83a.mkv
System.IO.IOException: The process cannot access the file 'C:\jellyfin\transcode\transcoding-temp\28abad54e8a5ed1ca03d7f36c7a9d83a.mkv' because it is being used by another process.
at System.IO.FileSystem.DeleteFile(String fullPath)
at System.IO.File.Delete(String path)
at MediaBrowser.Api.ApiEntryPoint.DeletePartialStreamFiles(String path, TranscodingJobType jobType, Int32 retryCount, Int32 delayMs)
```

![Captura](https://user-images.githubusercontent.com/48911173/56733804-855f7a80-6737-11e9-877c-9d24f1760662.JPG)

**Comment by dkanada** [comment]
@fagervan can you confirm this issue has been resolved in the latest release?

**Comment by fagervan** [comment]
> @fagervan can you confirm this issue has been resolved in the latest release?

yes. it is fixed.
