### ISSUE TITLE
error when sending content through DLNA device

### ISSUE THREAD

**Issue by 97carmine** [jellyfin/jellyfin-android#148]
When you select a DLNA device to send content to, nothing happens.

but the log shows the following:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: baseUrl
   at MediaBrowser.Model.Dlna.StreamInfo.ToUrl(String baseUrl, String accessToken)
   at Emby.Dlna.PlayTo.PlayToController.CreatePlaylistItem(BaseItem item, User user, Int64 startPostionTicks, String mediaSourceId, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex)
   at Emby.Dlna.PlayTo.PlayToController.SendPlayCommand(PlayRequest command, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendMessageToSession[T](SessionInfo session, String name, T data, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendPlayCommand(String controllingSessionId, String sessionId, PlayRequest command, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by nonplusnl** [comment]
Indeed looks like the same bug as #1456. Downgrading to 10.2.x helps (if you still have a users.db around for that version).

**Comment by 97carmine** [comment]
Fixed by: https://github.com/jellyfin/jellyfin/issues/1464#issuecomment-505810523
