### ISSUE TITLE
MediaCodecVideoRenderer error

### ISSUE THREAD

**Issue by bl4xe** [jellyfin/jellyfin-android#1495]
### Describe the bug

This is something I have experienced multiple times now. After uploading some new files to my Jellyfin server, I get this error when trying to play them. I am pretty certain it is the same bug that is also described in this thread:
https://github.com/google/ExoPlayer/issues/8509
It is important to note that I can still play files I uploaded some longer time ago, this only affects the newly uploaded files. This leads me to believe it is the same bug described on this post of the Jellyfin forum:
https://forum.jellyfin.org/t-solved-all-new-videos-won-t-play-anymore
I first thought I waa experiencing the same issue as the user in this thread is describing:
https://github.com/jellyfin/jellyfin-android/issues/1014
however he is getting an unsupported format error, the error I'm getting is different.
![Screenshot_20241016_031412_Jellyfin](https://github.com/user-attachments/assets/b4dad368-ecb7-4762-b322-8c8539dc8b0c)

### Application version

2.6.2

### Where did you install the app from?

Sideloaded APK (proprietary build)

### Device information

Samsung Galaxy A23

### Android version

Android 14

### Jellyfin server version

10.9.11

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by bl4xe** [comment]
Also I was just looking through the logs but I can't find the error message I got on my phone anywhere in them, let me know if there might be something useful in there either way and I will make sure to upload them

**Comment by AtomicCollapse** [comment]
+1

**Comment by yar-sh** [comment]
I think I'm running into the same issue. What worked for me is lowering the video quality to 1080p 10MB. Anything higher than 10MB bitrate gives this error (4K doesn't work too). This is not the perfect fix, I wonder what the issue is

**Comment by bobby3605** [comment]
I'm having this issue on my S24 Ultra with h264 10 bit video on exoplayer. MPV works fine.
I ran jellyfin-android through android studio with ADB debugging, and it looks like the problem for me is that the AVC decoder doesn't support h264 10 bit. This would seem to be an exoplayer or samsung or qualcomm issue. However, maybe jellyfin can transcode to h264 8 bit, or another viable format, if it detects that the decode failed.
```
2024-12-05 00:03:26.443 18685-27784 CCodec                  org.jellyfin.mobile.debug            I  [c2.qti.avc.decoder] state->set(RUNNING)
2024-12-05 00:03:26.443 18685-27784 CCodecBufferChannel     org.jellyfin.mobile.debug            I  [c2.qti.avc.decoder#779] 10 initial input buffers available
2024-12-05 00:03:26.444 18685-27780 MediaCodecInfo          org.jellyfin.mobile.debug            D  NoSupport [codec.profileLevel, avc1.6E0034, video/avc] [c2.qti.avc.decoder, video/avc] [e3q, SM-S928U, samsung, 34]
2024-12-05 00:03:26.444 18685-27780 MediaCodecRenderer      org.jellyfin.mobile.debug            W  Format exceeds selected codec's capabilities [id=1, mimeType=video/avc, codecs=avc1.6E0034, res=1920x1080, language=en, selectionFlags=[default], c2.qti.avc.decoder]
2024-12-05 00:03:26.445 18685-27783 MediaCodec              org.jellyfin.mobile.debug            I  setCodecState state(0), called in 6
2024-12-05 00:03:26.451 18685-19808 CCodec                  org.jellyfin.mobile.debug            D  Component "c2.qti.avc.decoder" returned error: 0xffffffff
2024-12-05 00:03:26.452 18685-27783 MediaCodec              org.jellyfin.mobile.debug            E  Codec reported err 0x80000000/UNKNOWN_ERROR, actionCode 0, while in state 6/STARTED
2024-12-05 00:03:26.452 18685-27783 MediaCodec              org.jellyfin.mobile.debug            D  flushMediametrics
2024-12-05 00:03:26.452 18685-27783 SurfaceUtils            org.jellyfin.mobile.debug            D  disconnecting from surface 0xb400007bdf87fbf0, reason disconnectFromSurface
2024-12-05 00:03:26.452 18685-27783 MediaCodec              org.jellyfin.mobile.debug            E  queueInputBuffer() is valid only at Executing states; currently at Released state
2024-12-05 00:03:26.452 18685-27783 MediaCodec              org.jellyfin.mobile.debug            E  queueInputBuffer() is valid only at Executing states; currently at Released state
2024-12-05 00:03:26.453 18685-27783 MediaCodec              org.jellyfin.mobile.debug            E  queueInputBuffer() is valid only at Executing states; currently at Released state
2024-12-05 00:03:26.453 18685-27783 MediaCodec              org.jellyfin.mobile.debug            E  queueInputBuffer() is valid only at Executing states; currently at Released state
2024-12-05 00:03:26.453 18685-27783 MediaCodec              org.jellyfin.mobile.debug            E  queueInputBuffer() is valid only at Executing states; currently at Released state
2024-12-05 00:03:26.453 18685-27783 MediaCodec              org.jellyfin.mobile.debug            E  queueInputBuffer() is valid only at Executing states; currently at Released state
2024-12-05 00:03:26.453 18685-27783 MediaCodec              org.jellyfin.mobile.debug            E  queueInputBuffer() is valid only at Executing states; currently at Released state
2024-12-05 00:03:26.453 18685-27783 MediaCodec              org.jellyfin.mobile.debug            E  queueInputBuffer() is valid only at Executing states; currently at Released state
2024-12-05 00:03:26.459 18685-27780 MediaCodecVideoRenderer org.jellyfin.mobile.debug            E  Video codec error
                                                                                                      java.lang.IllegalStateException: queueInputBuffer() is valid only at Executing states; currently at Released state
                                                                                                      
                                                                                                          at android.media.MediaCodec.native_queueInputBuffer(Native Method)
                                                                                                          at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2831)
                                                                                                          at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecBufferEnqueuer.doQueueInputBuffer(AsynchronousMediaCodecBufferEnqueuer.java:233)
                                                                                                          at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecBufferEnqueuer.doHandleMessage(AsynchronousMediaCodecBufferEnqueuer.java:206)
                                                                                                          at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecBufferEnqueuer.access$000(AsynchronousMediaCodecBufferEnqueuer.java:53)
                                                                                                          at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecBufferEnqueuer$1.handleMessage(AsynchronousMediaCodecBufferEnqueuer.java:102)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                          at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                          at android.os.Looper.loop(Looper.java:319)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
2024-12-05 00:03:26.459 18685-27780 MediaCodecInfo          org.jellyfin.mobile.debug            D  NoSupport [codec.profileLevel, avc1.6E0034, video/avc] [c2.qti.avc.decoder, video/avc] [e3q, SM-S928U, samsung, 34]
2024-12-05 00:03:26.459 18685-27780 MediaCodecInfo          org.jellyfin.mobile.debug            D  NoSupport [codec.profileLevel, avc1.6E0034, video/avc] [c2.qti.avc.decoder.low_latency, video/avc] [e3q, SM-S928U, samsung, 34]
2024-12-05 00:03:26.460 18685-27780 ExoPlayerImplInternal   org.jellyfin.mobile.debug            E  Playback error
                                                                                                      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.6E0034, -1, en, [1920, 1080, -1.0, null], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                          at android.os.Looper.loop(Looper.java:319)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                      Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.qti.avc.decoder
                                                                                                          at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1864)
                                                                                                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:843)
                                                                                                          at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:854)
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)
```

**Comment by ryry2nd** [comment]
Same issue for the A53 except it errors at anything over 1.5 Mbps

**Comment by kirides** [comment]
Probably related to #1538

Jellyfin seems to not differentiate Video bit-ness for playback support, neither does it transcode if the video Bitrate selected exceeds the video at hand

**Comment by IceStormNG** [comment]
I also ran into it an debugged it a bit. When you use exoplayer, the app does not send codec profiles to the server:

An empty array is created

https://github.com/jellyfin/jellyfin-android/blob/51c0e585d9a9f22be24db9d848f8386987f65221/app/src/main/java/org/jellyfin/mobile/player/deviceprofile/DeviceProfileBuilder.kt#L101

and here it is submitted. Nothing was added to it in between.

https://github.com/jellyfin/jellyfin-android/blob/51c0e585d9a9f22be24db9d848f8386987f65221/app/src/main/java/org/jellyfin/mobile/player/deviceprofile/DeviceProfileBuilder.kt#L139-L149


I checked the server with a debugger, and CodecProfile is empty, therefore, the server sees "h264", video says "h264", so it should work, at least from the point of view of the server.

The web-player seems to submit these codec info, which triggers a transcode for me.

For me the problem is H264 High 10, which my Android phone cannot play, but it doesn't tell the server, so no transcode is happening.

**Comment by Ginpachi98** [comment]
I am facing same issue, when HEVC file is played on  RK3229 it says playback error, re-try. It thinks it can play the HEVC, which it can't, so it doesn't request H264 transcode, meaning: it'd be nice to be able to set acceptable formats per device.

**Comment by Max-Pare** [comment]
This is happening on my A33 (Android 14) too

**Comment by randomzebra** [comment]
> Same issue for the A53 except it errors at anything over 1.5 Mbps

This has been happening in my s24 running Android 14. Same codec, same fix in terms of bit rate. If I get a chance I'll see if I can get some logging.

**Comment by schmilly** [comment]
Can confirm happening on Moto G54 5G Running Android 15

**Comment by HanSolo71** [comment]
Can firm also having this on pixel 8. Transcoding works as a workaround.

**Comment by PtitBeescuit** [comment]
Same problem when I play from my Redmi Note 11 Pro 5G with HyperOS 1.0.12.0TKCMIXM from Xiaomi.eu
Android 13

**Comment by ryry2nd** [comment]
I suggest you just swap out clients by eather using vlc or whatever video app you want or swapping the whole app for findroid because jellyfin's client is pretty bad. For me this was the only solution I could find.

**Comment by Choomai** [comment]
Is there any workarounds?

**Comment by Floordb** [comment]
I changed it to 720p and that seems to work. But it will transcode.

**Comment by Max-Pare** [comment]
> Is there any workarounds?

I switched to Findroid

**Comment by l0stpt** [comment]
This issue is still happening to this day, this happens when trying to play x265 files and some 10bit files, tried it on some of my android devices and all of them had the same problem.

Is it going to get fixed?

**Comment by Max-Pare** [comment]
> This issue is still happening to this day, this happens when trying to play x265 files and some 10bit files, tried it on some of my android devices and all of them had the same problem.
> 
> Is it going to get fixed?

not a direct solution but I've switched to Findroid which has worked very well the past few months. It's a Jellyfin client for Android and it's quite polished imo.

**Comment by mkhaledahmed** [comment]
Hey guys.

I know this is completed but I would like to mention that switching the quality to 1080p 10mbps or below fixed this issue. Going above that will trigger the mediacodecvideorenderer error.

**Comment by Choomai** [comment]
> Hey guys.
> 
> I know this is completed but I would like to mention that switching the quality to 1080p 10mbps or below fixed this issue. Going above that will trigger the mediacodecvideorenderer error.

isn't this fixed already?

**Comment by l0stpt** [comment]
> > Hey guys.
> > I know this is completed but I would like to mention that switching the quality to 1080p 10mbps or below fixed this issue. Going above that will trigger the mediacodecvideorenderer error.
> 
> isn't this fixed already?

nop

**Comment by jimbobur** [comment]
Having this exact issue with 1080p HEVC SDR 10-bit (codec tag hvc1) mp4 files. Why did the devs close this issue when it's not fixed?

**Comment by randomzebra** [comment]
> Having this exact issue with 1080p HEVC SDR 10-bit (codec tag hvc1) mp4 files. Why did the devs close this issue when it's not fixed?

It's fixed but not in an official released version. You can build and install this yourself if you need this immediately.

**Comment by jimbobur** [comment]
> > Having this exact issue with 1080p HEVC SDR 10-bit (codec tag hvc1) mp4 files. Why did the devs close this issue when it's not fixed?
> 
> It's fixed but not in an official released version. You can build and install this yourself if you need this immediately.

Just saw my bug closed as a duplicate of this one. I can directly play the video file on my phone in VLC. Am I misunderstanding or does the fix merged in https://github.com/jellyfin/jellyfin-android/pull/1889 simply force a transcode?

Also, unlike https://github.com/jellyfin/jellyfin-android/issues/1495 the Jellyfin web player in the android client also fails to play the file.

**Comment by GhostDog98** [comment]
@nielsvanvelzen is it possible we could get this issue re-examined? I am still seeing this issue after building from source (commit #1948 146db28af569407d4c2876552e86760f302d9d0b)
My clone does contain the "fix" as implemented in #1889 (e421a0bbcc51c4662de0538381b5a214907fd830) as running `git branch --contains <hash>` shows it is present.

**Comment by GhostDog98** [comment]
I also have a debug log if that helps

**Comment by nielsvanvelzen** [comment]
> [@nielsvanvelzen](https://github.com/nielsvanvelzen) is it possible we could get this issue re-examined? I am still seeing this issue after building from source (commit [#1948](https://github.com/jellyfin/jellyfin-android/pull/1948) [146db28](https://github.com/jellyfin/jellyfin-android/commit/146db28af569407d4c2876552e86760f302d9d0b)) My clone does contain the "fix" as implemented in [#1889](https://github.com/jellyfin/jellyfin-android/pull/1889) ([e421a0b](https://github.com/jellyfin/jellyfin-android/commit/e421a0bbcc51c4662de0538381b5a214907fd830)) as running `git branch --contains <hash>` shows it is present.

If you're sure the fix isn't working, please open a new issue with details.
