### ISSUE TITLE
Crash when use Exoplayer

### ISSUE THREAD

**Issue by wsysx123** [jellyfin/jellyfin-android#1511]
### Describe the bug

server: 10.10.1
build version : 241114
Jellyfin Android Apk version: 2.6.2

The trace show not have libcronet.119.0.6045.31.so, How to install it?

### Logs

```shell
java.lang.RuntimeException: Cannot create an instance of class org.jellyfin.mobile.player.PlayerViewModel
 at androidx.lifecycle.d0.d(SourceFile:61)
 at androidx.lifecycle.d0.a(SourceFile:5)
 at androidx.lifecycle.d0.c(SourceFile:5)
 at androidx.lifecycle.a0.c(SourceFile:66)
 at P1.c.a(SourceFile:10)
 at androidx.lifecycle.a0.b(SourceFile:1)
 at C3.m.L(SourceFile:90)
 at N1.c.k(SourceFile:101)
 at A3.j.getValue(SourceFile:61)
 at org.jellyfin.mobile.player.ui.PlayerFragment.getViewModel(SourceFile:3)
 at org.jellyfin.mobile.player.ui.PlayerFragment.onCreate(SourceFile:4)
 at androidx.fragment.app.o.performCreate(SourceFile:22)
 at androidx.fragment.app.x.e(SourceFile:51)
 at androidx.fragment.app.x.k(SourceFile:180)
 at androidx.fragment.app.u.B(SourceFile:1124)
 at androidx.fragment.app.u.U(SourceFile:82)
 at androidx.fragment.app.u.z(SourceFile:78)
 at D1.m.run(SourceFile:730)
 at android.os.Handler.handleCallback(Handler.java:958)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:224)
 at android.os.Looper.loop(Looper.java:318)
 at android.app.ActivityThread.main(ActivityThread.java:8719)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.reflect.InvocationTargetException
 at java.lang.reflect.Constructor.newInstance0(Native Method)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
 at androidx.lifecycle.d0.d(SourceFile:27)
 ... 25 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libcronet.119.0.6045.31.so" not found
 at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
 at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
 at java.lang.System.loadLibrary(System.java:1661)
 at org.chromium.net.impl.CronetLibraryLoader.a(SourceFile:67)
 at org.chromium.net.impl.CronetUrlRequestContext.<init>(SourceFile:95)
 at Y6.g.b(SourceFile:15)
 at W6.e.b(SourceFile:15)
 at org.jellyfin.mobile.app.AppModuleKt.applicationModule$lambda$27$lambda$20(SourceFile:214)
 at org.jellyfin.mobile.app.AppModuleKt.t(SourceFile:1)
 at b7.a.invoke(SourceFile:1)
 at L7.b.a(SourceFile:48)
 at L7.c.a(SourceFile:5)
 at D.g.invoke(SourceFile:638)
 at L7.c.b(SourceFile:8)
 at R7.a.c(SourceFile:110)
 at R7.a.a(SourceFile:140)
 at org.jellyfin.mobile.app.AppModuleKt.applicationModule$lambda$27$lambda$22(SourceFile:54)
 at org.jellyfin.mobile.app.AppModuleKt.b(SourceFile:1)
 at b7.a.invoke(SourceFile:1)
 at L7.b.a(SourceFile:48)
 at L7.c.a(SourceFile:5)
 at D.g.invoke(SourceFile:638)
 at L7.c.b(SourceFile:8)
 at R7.a.c(SourceFile:110)
 at R7.a.a(SourceFile:140)
 at org.jellyfin.mobile.player.PlayerViewModel.setupPlayer(SourceFile:54)
 at org.jellyfin.mobile.player.interaction.PlayerLifecycleObserver.onCreate(SourceFile:8)
 at androidx.lifecycle.g.h(SourceFile:98)
 at androidx.lifecycle.y.a(SourceFile:23)
 at androidx.lifecycle.z.a(SourceFile:216)
 at org.jellyfin.mobile.player.PlayerViewModel.<init>(SourceFile:244)
 ... 28 more
```

### Application version

2.6.2

### Where did you install the app from?

Google Play

### Device information

Xiaomi HyperOS 1.0.21.0

### Android version

Android 14

### Jellyfin server version

10.10.1

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [x] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by wsysx123** [comment]
Fix after reinstall...
