### ISSUE TITLE
Chromecast cannot play

### ISSUE THREAD

**Issue by majora2007** [jellyfin/jellyfin-android#184]
I have a Chromecast v2 that I am trying to play media from Jellyfin Android app on. If I cast to the device then try and press the play button on the episode, but the play button acts "disabled" (aka doesn't do anything).

I also try playing the episode on my device then hitting the cast button, but once I hit the cast button the chromecast shows the "ready to cast jellyfin app", but nothing moves over there and the video on the phone stops.

Anyone else having this issue or is chromecast for Android not functional? 

Some extra info:
Jellyfin is hosted within same network on a wired connection using Windows and Caddy for HTTPS reverse proxy.

**Comment by anthonylavado** [comment]
@majora2007 Does it look like this - https://github.com/jellyfin/jellyfin-web/issues/440

**Comment by majora2007** [comment]
So here I've already connected to Chromecast and I'm trying to hit play button on top. The button doesn't seem clickable. No hover, no press, nothing. 

![Screenshot_2019-09-03-12-09-25](https://user-images.githubusercontent.com/735851/64194144-08aa7e80-ce44-11e9-8f39-bb6f5d67871e.jpg)

If I click Chromecast and hit remote control, yes, it looks like Issue 440. 

I have gotten chromecast to work when I was outside my local network, so perhaps this is a local network issue?

**Comment by anthonylavado** [comment]
@majora2007 Aha - if it works outside your local network, there's one more question.

Is this the app or the web browser?

**Comment by majora2007** [comment]
Yes, on all media I've tried so far. I tried the exact media that worked on another network (only tried one) and nothing worked. 

My caddy file is very simple:

```
proxy /emby localhost:8096 {
	transparent
	insecure_skip_verify
}
```

**Comment by majora2007** [comment]
Looks like it was a network issue. I followed the "short answer" here and added internal ip to hosts file.
https://caddy.community/t/grant-access-in-a-lan/2690

LAN now works. 

Chromecast does not it seems. I see this when I try to play a music track.

```
[2019-09-04 02:02:33.501 -05:00] [INF] ExecuteQueuedTasks
[2019-09-04 05:53:14.339 -05:00] [INF] "Destroyer" ("N:\Music\Destroyer") will be refreshed.
[2019-09-04 07:31:06.272 -05:00] [ERR] AcceptWebSocketAsync error
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Emby.Server.Implementations.SocketSharp.WebSocketSharpListener.ProcessWebSocketRequest(HttpContext ctx)
[2019-09-04 07:40:29.139 -05:00] [WRN] HTTP Response 200 to "192.168.1.254". Time (slow): 0:00:07.0650516. "http://majora2007.no-ip.biz/emby/emby/system/info/public"
```

**Comment by majora2007** [comment]
This issue seems to be due to my reverse proxy not working on LAN, rather than jellyfin itself.
