### ISSUE TITLE
Can't set up build environment

### ISSUE THREAD

**Issue by Rijul-A** [jellyfin/jellyfin-android#200]
The following commands, as outlined in the README.md (#185) throw an error
```
$ cd
$ cd Desktop
$ git clone https://github.com/jellyfin/jellyfin-android.git
$ cd jellyfin-android
$ npm install

> jellyfin-android@0.9.0 postinstall /home/rijul/Desktop/jellyfin-android
> gulp

Using jellyfin-web from node_modules/jellyfin-web/dist
[00:41:41] Using gulpfile ~/Desktop/jellyfin-android/gulpfile.js
[00:41:41] Starting 'default'...
[00:41:41] Starting 'clean'...
[00:41:41] Finished 'clean' after 4.84 ms
[00:41:41] Starting 'copy'...
[00:41:41] Starting 'modifyIndex'...
[00:41:41] Starting 'scripts'...
[00:41:41] Finished 'copy' after 20 ms
[00:41:41] 'modifyIndex' errored after 22 ms
[00:41:41] Error: File not found with singular glob: /home/rijul/Desktop/jellyfin-android/node_modules/jellyfin-web/dist/index.html (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/home/rijul/Desktop/jellyfin-android/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Glob.emit (events.js:211:7)
    at Glob._finish (/home/rijul/Desktop/jellyfin-android/node_modules/glob/glob.js:197:8)
    at done (/home/rijul/Desktop/jellyfin-android/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/home/rijul/Desktop/jellyfin-android/node_modules/glob/glob.js:688:12)
    at /home/rijul/Desktop/jellyfin-android/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/home/rijul/Desktop/jellyfin-android/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/home/rijul/Desktop/jellyfin-android/node_modules/glob/glob.js:764:12)
[00:41:41] 'default' errored after 29 ms
[00:41:41] The following tasks did not complete: scripts
[00:41:41] Did you forget to signal async completion?

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.9
npm WARN jellyfin-android@0.9.0 license should be a valid SPDX license expression
npm ERR! Linux 4.15.0-48-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! jellyfin-android@0.9.0 postinstall: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jellyfin-android@0.9.0 postinstall script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jellyfin-android package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jellyfin-android
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jellyfin-android
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rijul/Desktop/jellyfin-android/npm-debug.log
```

The full debug log is available [here](https://rijul.me/jellyfin-npm-debug.log). I've tried some Google-fu but didn't have so much luck, if anyone knows how to fix this, please help. Thanks!

**Comment by anthonylavado** [comment]
It’s an error if the wrong version of jellyfin-web is pulled. It should be using `master`...

**Comment by anthonylavado** [comment]
@thornbill I forget how I got this working. Any thoughts?

**Comment by thornbill** [comment]
I suspect this may be an issue with the version of node you have installed. From the logs it looks like you are using `v8.10.0`. This project installs jellyfin-web directly from the git repository (see https://github.com/jellyfin/jellyfin-android/blob/master/package.json#L25). Older versions of node had some issues with not running the appropriate scripts when installing dependencies in this way.

Would it be possible for you to upgrade the version of node you are using? All support for 8.x is scheduled to end in December. https://github.com/nodejs/Release#release-schedule

**Comment by Rijul-A** [comment]
Thanks @thornbill, this fixed my problem.
```
$ curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
$ sudo apt install -y nodejs
```

**Comment by Rijul-A** [comment]
Hey, another question here, everytime I make a change in a file, it doesn't reflect correctly in the platforms folder when building. I discovered a workaround, which is to clone the repo again, make the changes, and then use node to do everything else. Is that expected to be this way or is something wrong with my set up?

**Comment by anthonylavado** [comment]
What changes are you making?
Is it to the Web files?

**Comment by Rijul-A** [comment]
No, just the Java files.
