### ISSUE TITLE
Identifying with "The Open Movie Database" crashes on a TV show specific request

### ISSUE THREAD

**Issue by nsvir** [jellyfin/jellyfin-android#212]
# A request to identify a TV shows crashes
When I try to identify the tv show "Castle" with "The Open Movie Database", the app crashes.

## To reproduce
1. Go to a tv show library and make sure it uses "The Open Movie Database" to fetch the metadata
2. Pick any tv show and identify it
3. In the "name" field, type "Castle"
4. Press enter, the app should crash

## Expected
App should not crash. If data is corrupted it should ignore the specific results and still show the others.

## Logs
```log
FATAL EXCEPTION: main
Process: org.jellyfin.mobile, PID: 5873
java.lang.IllegalArgumentException: reasonPhrase can't be empty.
at android.webkit.WebResourceResponse.setStatusCodeAndReasonPhrase(WebResourceResponse.java:151)
at android.webkit.WebResourceResponse.(WebResourceResponse.java:89)
at mK.a(PG:646)
at yL.handleMessage(PG:218)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6718)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

## System
 - App version: 2.1.1
 - Android version: LineageOs 16.0, Android 9
 - Device manufacturer and model: Moto G5
 - Jellyfin server version: 10.6.4

**Comment by Maxr1998** [comment]
I suspect that's an error either in the Android framework, the libraries or caused by the webclient - but I can't tell with 100% certainty without seeing a full stack trace. Could you try to reproduce this on the debug client? You can download it from the releases page as well.
