### ISSUE TITLE
Casting fails on 2.0.1

### ISSUE THREAD

**Issue by briandipalma** [jellyfin/jellyfin-android#238]
**Describe the bug**
I can login to Jellyfin via the web UI and the android app. I can play videos on my phone but when I cast they stop and if I cast and play nothing happens. The TV screen does show the Jellyfin logo but nothing is played. I've used VLC on a laptop and on my phone to cast URL streams successfully. I tried using the nightly chromecast driver but it seems to have no effect (I killed the app and restarted, should I log out?).

**Logs**
```
[2020-11-16 22:25:08.645 +00:00] [WRN] [103] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.1.17". Time (slow): 0:00:00.8088331. "http://srv:8096/Users/80b58ad3326c48cd9ea3457a1227e9c0"
[2020-11-16 22:25:08.766 +00:00] [WRN] [87] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.1.17". Time (slow): 0:00:00.9291757. "http://srv:8096/Users/80b58ad3326c48cd9ea3457a1227e9c0/Views"
[2020-11-16 22:25:18.080 +00:00] [ERR] [87] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://srv:8096/System/Configuration/cinemamode"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Configuration with key cinemamode not found.
   at Emby.Server.Implementations.AppBase.BaseConfigurationManager.<>c__DisplayClass42_0.<GetConfiguration>b__0(String k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.Api.ConfigurationService.Get(GetNamedConfiguration request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-11-16 22:25:27.057 +00:00] [WRN] [103] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "192.168.1.17". Time (slow): 0:00:00.6338684. "http://srv:8096/Users/80b58ad3326c48cd9ea3457a1227e9c0/Configuration"
[2020-11-16 22:25:27.723 +00:00] [WRN] [83] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "192.168.1.17". Time (slow): 0:00:01.2340437. "http://srv:8096/DisplayPreferences/usersettings?userId=80b58ad3326c48cd9ea3457a1227e9c0&client=emby"
[2020-11-16 22:25:36.056 +00:00] [WRN] [98] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "::ffff:192.168.1.17" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2020-11-16 22:25:36.057 +00:00] [INF] [98] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:192.168.1.17" closed
[2020-11-16 22:25:43.174 +00:00] [INF] [80] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:192.168.1.17" request
[2020-11-16 22:26:39.116 +00:00] [ERR] [83] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://srv:8096/System/Configuration/cinemamode"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Configuration with key cinemamode not found.
   at Emby.Server.Implementations.AppBase.BaseConfigurationManager.<>c__DisplayClass42_0.<GetConfiguration>b__0(String k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.Api.ConfigurationService.Get(GetNamedConfiguration request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-11-16 22:26:46.125 +00:00] [WRN] [80] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.1.17". Time (slow): 0:00:00.8339036. "http://srv:8096/DisplayPreferences/usersettings?userId=80b58ad3326c48cd9ea3457a1227e9c0&client=emby"
[2020-11-16 22:26:52.087 +00:00] [WRN] [106] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "::ffff:192.168.1.17" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2020-11-16 22:26:52.088 +00:00] [INF] [106] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:192.168.1.17" closed
```

**System (please complete the following information):**
 - App version: 2.0.1
 - Android version: Android 9
 - Device manufacturer and model: OnePlus 3T
 - Jellyfin server version: 10.6.4
 - The type of video player implementation used: web player (I'm guessing this is irrelevant for casting?)

I've read the logcat website but I don't understand where I'm meant to run it. My device isn't rooted and I don't see what running `adb` in the Jellyfin Docker container would achieve...

This used to work 4 months ago, the only change from then is that my Ubuntu Server is now running in a VM on Proxmox but it has it's own IP address and VLC can cast successfully and of course a newer version of the android app.

**Comment by nielsvanvelzen** [comment]
Possibly related to jellyfin/jellyfin#3712 / jellyfin/jellyfin#3852.

**Comment by briandipalma** [comment]
https://github.com/jellyfin/jellyfin/issues/4616 is probably the right place for this issue as it's broken in web client as well.
