### ISSUE TITLE
TLSv1.3 not supported

### ISSUE THREAD

**Issue by Serranya** [jellyfin/jellyfin-android#248]
**Describe the bug**
When I try to connect to my jellyfin instance I get an error that the app can not connect.

**To Reproduce**
1. Open app
2. Enter `https://chill.peterlamby.de` (try it. the server is public)
3. Error

**Expected behavior**
The app should connect

**Logs**
I got the following stacktrace with logcat:
```
1-22 08:55:59.317 18811 18811 E e$b     : VolleyError com.android.volley.NoConnectionError: javax.net.ssl.SSLHandshakeException: Handshake failed
11-22 08:55:59.317 18811 18811 E e$b     : com.android.volley.NoConnectionError: javax.net.ssl.SSLHandshakeException: Handshake failed
11-22 08:55:59.317 18811 18811 E e$b     : 	at j.a.b.o.b.f(BasicNetwork.java:33)
11-22 08:55:59.317 18811 18811 E e$b     : 	at j.a.b.h.a(NetworkDispatcher.java:8)
11-22 08:55:59.317 18811 18811 E e$b     : 	at j.a.b.h.run(NetworkDispatcher.java:2)
11-22 08:55:59.317 18811 18811 E e$b     : Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
11-22 08:55:59.317 18811 18811 E e$b     : 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:302)
11-22 08:55:59.317 18811 18811 E e$b     : 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1480)
11-22 08:55:59.317 18811 18811 E e$b     : 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1424)
11-22 08:55:59.317 18811 18811 E e$b     : 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1368)
11-22 08:55:59.317 18811 18811 E e$b     : 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:219)
11-22 08:55:59.317 18811 18811 E e$b     : 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:142)
11-22 08:55:59.317 18811 18811 E e$b     : 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:104)
11-22 08:55:59.317 18811 18811 E e$b     : 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:392)
11-22 08:55:59.317 18811 18811 E e$b     : 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:325)
11-22 08:55:59.317 18811 18811 E e$b     : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:470)
11-22 08:55:59.317 18811 18811 E e$b     : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:416)
11-22 08:55:59.317 18811 18811 E e$b     : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:547)
11-22 08:55:59.317 18811 18811 E e$b     : 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
11-22 08:55:59.317 18811 18811 E e$b     : 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
11-22 08:55:59.317 18811 18811 E e$b     : 	at j.a.b.o.f.a(HurlStack.java:18)
11-22 08:55:59.317 18811 18811 E e$b     : 	at j.a.b.o.b.f(BasicNetwork.java:5)
11-22 08:55:59.317 18811 18811 E e$b     : 	... 2 more
11-22 08:55:59.317 18811 18811 E e$b     : Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x79ad44f988: Failure in SSL library, usually a protocol error
11-22 08:55:59.317 18811 18811 E e$b     : error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (external/boringssl/src/ssl/tls_record.cc:592 0x79ad44b088:0x00000001)
11-22 08:55:59.317 18811 18811 E e$b     : 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
11-22 08:55:59.317 18811 18811 E e$b     : 	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:383)
11-22 08:55:59.317 18811 18811 E e$b     : 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
11-22 08:55:59.317 18811 18811 E e$b     : 	... 17 more
11-22 08:55:59.318 18811 18811 E i       : org.jellyfin.apiclient.model.net.HttpException: VolleyError com.android.volley.NoConnectionError:
11-22 08:55:59.318 18811 18811 E i       : 	at j.a.b.e$b.run(ExecutorDelivery.java:12)
11-22 08:55:59.318 18811 18811 E i       : 	at android.os.Handler.handleCallback(Handler.java:873)
11-22 08:55:59.318 18811 18811 E i       : 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-22 08:55:59.318 18811 18811 E i       : 	at android.os.Looper.loop(Looper.java:214)
11-22 08:55:59.318 18811 18811 E i       : 	at android.app.ActivityThread.main(ActivityThread.java:7050)
11-22 08:55:59.318 18811 18811 E i       : 	at java.lang.reflect.Method.invoke(Native Method)
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
11-22 08:55:59.318 18811 18811 E i       : Caused by: com.android.volley.NoConnectionError: javax.net.ssl.SSLHandshakeException: Handshake failed
11-22 08:55:59.318 18811 18811 E i       : 	at j.a.b.o.b.f(BasicNetwork.java:33)
11-22 08:55:59.318 18811 18811 E i       : 	at j.a.b.h.a(NetworkDispatcher.java:8)
11-22 08:55:59.318 18811 18811 E i       : 	at j.a.b.h.run(NetworkDispatcher.java:2)
11-22 08:55:59.318 18811 18811 E i       : Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:302)
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1480)
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1424)
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1368)
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:219)
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:142)
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:104)
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:392)
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:325)
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:470)
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:416)
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:547)
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
11-22 08:55:59.318 18811 18811 E i       : 	at j.a.b.o.f.a(HurlStack.java:18)
11-22 08:55:59.318 18811 18811 E i       : 	at j.a.b.o.b.f(BasicNetwork.java:5)
11-22 08:55:59.318 18811 18811 E i       : 	... 2 more
11-22 08:55:59.318 18811 18811 E i       : Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x79ad44f988: Failure in SSL library, usually a protocol error
11-22 08:55:59.318 18811 18811 E i       : error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (external/boringssl/src/ssl/tls_record.cc:592 0x79ad44b088:0x00000001)
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:383)
11-22 08:55:59.318 18811 18811 E i       : 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
11-22 08:55:59.318 18811 18811 E i       : 	... 17 more
11-22 08:55:59.318 18811 18811 W ConnectFragment$checkServerUrlAndConnection: Failed to find server info, url was https://chill.peterlamby.de/
```

**System (please complete the following information):**
 - App version: 2.2 from the playstore
 - Android version: 9
 - Device manufacturer and model: Samsung Galaxy S9
 - Jellyfin server version: 10.6.4
 - I use Apache as reverseProxy for SSL termination

**Additional context**
For the SSL config see here: https://www.ssllabs.com/ssltest/analyze.html?d=chill.peterlamby.de&s=176.9.53.207

**Comment by Maxopoly** [comment]
This is fixed as of Android 10, which has builtin support for TLSv1.3

**Comment by nielsvanvelzen** [comment]
Like @Maxopoly says, TLS 1.3 is only supported in Android 10 and up. If you use an older Android version you should use a different protocol.

**Comment by Serranya** [comment]
Hmm too bad. Im on Android 9. But thanks for the info. I will allow TLS 1.2 on the Server.
