### ISSUE TITLE
Azure pipeline often crashes during the "Build Release" task

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-android#251]
**Describe the bug**

A few weeks ago the Azure pipeline started crashing during the "Build Release" task. This issue is becoming more regular and needs to be fixed ASAP. It already caused us issues with  the 2.2.0 release and also doesn't help when reviewing pull requests either.

**To Reproduce**
1. Trigger build

**Expected behavior**
The build should only fail when there is an actual issue.

**Logs**
<details>

```
2020-11-21T12:29:52.5510813Z ##[section]Starting: Build Release
2020-11-21T12:29:52.5530421Z ==============================================================================
2020-11-21T12:29:52.5531343Z Task         : Gradle
2020-11-21T12:29:52.5531784Z Description  : Build using a Gradle wrapper script
2020-11-21T12:29:52.5532212Z Version      : 2.178.0
2020-11-21T12:29:52.5532753Z Author       : Microsoft Corporation
2020-11-21T12:29:52.5533262Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/gradle
2020-11-21T12:29:52.5533823Z ==============================================================================
2020-11-21T12:29:53.0699101Z ##[warning]Resource file has already set to: /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
2020-11-21T12:29:53.0711769Z ##[warning]Resource file has already set to: /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
2020-11-21T12:29:53.0748039Z ##[warning]Resource file has already set to: /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
2020-11-21T12:29:53.0787036Z ##[warning]Resource file has already set to: /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
2020-11-21T12:29:53.0806305Z ##[warning]Resource file has already set to: /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
2020-11-21T12:29:53.1447147Z SYSTEMVSSCONNECTION exists true
2020-11-21T12:29:53.1448762Z [command]/home/vsts/work/1/s/gradlew assembleRelease
2020-11-21T12:29:54.8578986Z > Task :buildSrc:compileKotlin UP-TO-DATE
2020-11-21T12:29:54.8580851Z > Task :buildSrc:compileJava NO-SOURCE
2020-11-21T12:29:54.8592050Z > Task :buildSrc:compileGroovy NO-SOURCE
2020-11-21T12:29:54.8597562Z > Task :buildSrc:pluginDescriptors UP-TO-DATE
2020-11-21T12:29:54.8601751Z > Task :buildSrc:processResources NO-SOURCE
2020-11-21T12:29:54.8606424Z > Task :buildSrc:classes UP-TO-DATE
2020-11-21T12:29:54.8629707Z > Task :buildSrc:inspectClassesForKotlinIC UP-TO-DATE
2020-11-21T12:29:54.8632088Z > Task :buildSrc:jar UP-TO-DATE
2020-11-21T12:29:54.8633168Z > Task :buildSrc:assemble UP-TO-DATE
2020-11-21T12:29:54.8638258Z > Task :buildSrc:compileTestKotlin NO-SOURCE
2020-11-21T12:29:54.8653322Z > Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
2020-11-21T12:29:54.8654492Z > Task :buildSrc:compileTestJava NO-SOURCE
2020-11-21T12:29:54.8655313Z > Task :buildSrc:compileTestGroovy NO-SOURCE
2020-11-21T12:29:54.8656179Z > Task :buildSrc:processTestResources NO-SOURCE
2020-11-21T12:29:54.8656987Z > Task :buildSrc:testClasses UP-TO-DATE
2020-11-21T12:29:54.8657718Z > Task :buildSrc:test NO-SOURCE
2020-11-21T12:29:54.8658731Z > Task :buildSrc:validatePlugins UP-TO-DATE
2020-11-21T12:29:54.8665159Z > Task :buildSrc:check UP-TO-DATE
2020-11-21T12:29:54.8666224Z > Task :buildSrc:build UP-TO-DATE
2020-11-21T12:30:13.6220893Z > Task :app:preBuild UP-TO-DATE
2020-11-21T12:30:13.6221931Z > Task :app:extractProguardFiles
2020-11-21T12:30:13.6222691Z > Task :app:preLibreReleaseBuild
2020-11-21T12:30:13.6224069Z > Task :app:compileLibreReleaseAidl NO-SOURCE
2020-11-21T12:30:13.6224769Z > Task :app:compileLibreReleaseRenderscript NO-SOURCE
2020-11-21T12:30:13.6225173Z > Task :app:dataBindingMergeDependencyArtifactsLibreRelease
2020-11-21T12:30:13.6225658Z > Task :app:dataBindingMergeGenClassesLibreRelease
2020-11-21T12:30:13.6225995Z > Task :app:generateLibreReleaseResValues
2020-11-21T12:30:13.6226377Z > Task :app:generateLibreReleaseResources
2020-11-21T12:30:15.8521910Z > Task :app:generateLibreReleaseBuildConfig
2020-11-21T12:30:15.8537882Z > Task :app:checkLibreReleaseAarMetadata
2020-11-21T12:30:15.9521339Z > Task :app:createLibreReleaseCompatibleScreenManifests
2020-11-21T12:30:15.9524025Z > Task :app:extractDeepLinksLibreRelease
2020-11-21T12:30:16.0524430Z > Task :app:processLibreReleaseMainManifest
2020-11-21T12:30:16.0540895Z > Task :app:processLibreReleaseManifest
2020-11-21T12:30:16.0541963Z > Task :app:processLibreReleaseManifestForPackage
2020-11-21T12:30:16.0542672Z > Task :app:javaPreCompileLibreRelease
2020-11-21T12:30:16.1521843Z > Task :app:mergeLibreReleaseNativeDebugMetadata NO-SOURCE
2020-11-21T12:30:16.5525321Z > Task :app:mergeLibreReleaseResources
2020-11-21T12:30:16.5527094Z > Task :app:mergeLibreReleaseShaders
2020-11-21T12:30:16.6521348Z > Task :app:dataBindingGenBaseClassesLibreRelease
2020-11-21T12:30:17.3545330Z warn: removing resource org.jellyfin.mobile:string/mediaservice_library_albums without required default value.
2020-11-21T12:30:17.3546530Z warn: removing resource org.jellyfin.mobile:string/mediaservice_library_artists without required default value.
2020-11-21T12:30:17.3547107Z warn: removing resource org.jellyfin.mobile:string/mediaservice_library_genres without required default value.
2020-11-21T12:30:17.3547720Z warn: removing resource org.jellyfin.mobile:string/mediaservice_library_latest without required default value.
2020-11-21T12:30:17.3548366Z warn: removing resource org.jellyfin.mobile:string/mediaservice_library_playlists without required default value.
2020-11-21T12:30:17.3548924Z warn: removing resource org.jellyfin.mobile:string/mediaservice_library_songs without required default value.
2020-11-21T12:30:17.3549509Z warn: removing resource org.jellyfin.mobile:string/mediaservice_shuffle without required default value.
2020-11-21T12:30:17.3550113Z warn: removing resource org.jellyfin.mobile:string/pref_enable_exoplayer_summary without required default value.
2020-11-21T12:30:17.3550663Z warn: removing resource org.jellyfin.mobile:string/pref_enable_exoplayer_title without required default value.
2020-11-21T12:30:17.3551046Z 
2020-11-21T12:30:17.4525105Z > Task :app:processLibreReleaseResources
2020-11-21T12:30:21.5523072Z > Task :app:kaptGenerateStubsLibreReleaseKotlin
2020-11-21T12:30:21.9528788Z > Task :app:compileLibreReleaseShaders NO-SOURCE
2020-11-21T12:30:21.9530373Z > Task :app:generateLibreReleaseAssets UP-TO-DATE
2020-11-21T12:30:21.9531348Z > Task :app:mergeLibreReleaseAssets
2020-11-21T12:30:22.0521983Z > Task :app:compressLibreReleaseAssets
2020-11-21T12:30:22.1522105Z > Task :app:checkLibreReleaseDuplicateClasses
2020-11-21T12:30:22.2522682Z > Task :app:processLibreReleaseJavaRes NO-SOURCE
2020-11-21T12:30:22.6522226Z > Task :app:collectLibreReleaseDependencies
2020-11-21T12:30:22.7522288Z > Task :app:sdkLibreReleaseDependencyData
2020-11-21T12:30:22.7527247Z > Task :app:mergeLibreReleaseJniLibFolders
2020-11-21T12:30:23.3526430Z > Task :app:mergeLibreReleaseNativeLibs
2020-11-21T12:30:23.3528582Z > Task :app:stripLibreReleaseDebugSymbols NO-SOURCE
2020-11-21T12:30:23.3529429Z > Task :app:preProprietaryReleaseBuild
2020-11-21T12:30:23.3530763Z > Task :app:compileProprietaryReleaseAidl NO-SOURCE
2020-11-21T12:30:23.3531870Z > Task :app:compileProprietaryReleaseRenderscript NO-SOURCE
2020-11-21T12:30:23.4523676Z > Task :app:dataBindingMergeDependencyArtifactsProprietaryRelease
2020-11-21T12:30:23.4525310Z > Task :app:dataBindingMergeGenClassesProprietaryRelease
2020-11-21T12:30:23.4525851Z > Task :app:generateProprietaryReleaseResValues
2020-11-21T12:30:23.4526264Z > Task :app:generateProprietaryReleaseResources
2020-11-21T12:30:24.9543449Z 
2020-11-21T12:30:24.9544982Z > Task :app:kaptLibreReleaseKotlin
2020-11-21T12:30:25.5525271Z warning: Current JDK version 11.0.9.1+1 has a bug (https://bugs.openjdk.java.net/browse/JDK-8007720) that prevents Room from being incremental. Consider using JDK 11+ or the embedded JDK shipped with Android Studio 3.5+.[WARN] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: androidx.room.RoomProcessor (DYNAMIC).
2020-11-21T12:30:27.5521370Z 
2020-11-21T12:30:27.5522913Z > Task :app:mergeProprietaryReleaseResources
2020-11-21T12:30:37.2521094Z 
2020-11-21T12:30:37.2522581Z > Task :app:compileLibreReleaseKotlin
2020-11-21T12:30:37.2524086Z w: /home/vsts/work/1/s/app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt: (89, 30): Parameter 'target' is never used
2020-11-21T12:30:37.9536653Z 
2020-11-21T12:30:37.9538646Z > Task :app:compileLibreReleaseJavaWithJavac
2020-11-21T12:30:37.9539966Z > Task :app:compileLibreReleaseSources
2020-11-21T12:31:07.9824826Z > Task :app:lintVitalLibreRelease
2020-11-21T12:31:28.1521180Z > Task :app:mergeLibreReleaseGeneratedProguardFiles
2020-11-21T12:31:28.2526667Z > Task :app:dataBindingGenBaseClassesProprietaryRelease
2020-11-21T12:31:28.2528048Z > Task :app:generateProprietaryReleaseBuildConfig
2020-11-21T12:31:28.2528744Z > Task :app:checkProprietaryReleaseAarMetadata
2020-11-21T12:31:28.2529326Z > Task :app:createProprietaryReleaseCompatibleScreenManifests
2020-11-21T12:31:28.2529690Z > Task :app:extractDeepLinksProprietaryRelease
2020-11-21T12:31:28.4521924Z > Task :app:processProprietaryReleaseMainManifest
2020-11-21T12:31:28.4523384Z > Task :app:processProprietaryReleaseManifest
2020-11-21T12:31:28.4524123Z > Task :app:processProprietaryReleaseManifestForPackage
2020-11-21T12:31:31.1546014Z > Task :app:mergeLibreReleaseJavaResource
2020-11-21T12:31:32.0524354Z warn: removing resource org.jellyfin.mobile:string/mediaservice_library_albums without required default value.
2020-11-21T12:31:32.0526130Z warn: removing resource org.jellyfin.mobile:string/mediaservice_library_artists without required default value.
2020-11-21T12:31:32.0527736Z warn: removing resource org.jellyfin.mobile:string/mediaservice_library_genres without required default value.
2020-11-21T12:31:32.0528699Z warn: removing resource org.jellyfin.mobile:string/mediaservice_library_latest without required default value.
2020-11-21T12:31:32.0529761Z warn: removing resource org.jellyfin.mobile:string/mediaservice_library_playlists without required default value.
2020-11-21T12:31:32.0531373Z warn: removing resource org.jellyfin.mobile:string/mediaservice_library_songs without required default value.
2020-11-21T12:31:32.0532332Z warn: removing resource org.jellyfin.mobile:string/mediaservice_shuffle without required default value.
2020-11-21T12:31:32.0534005Z warn: removing resource org.jellyfin.mobile:string/pref_enable_exoplayer_summary without required default value.
2020-11-21T12:31:32.0535013Z warn: removing resource org.jellyfin.mobile:string/pref_enable_exoplayer_title without required default value.
2020-11-21T12:31:32.0535648Z 
2020-11-21T12:31:32.2520826Z > Task :app:processProprietaryReleaseResources
2020-11-21T12:31:39.8521276Z 
2020-11-21T12:31:39.8522604Z > Task :app:minifyLibreReleaseWithR8
2020-11-21T12:31:39.8523400Z R8: Missing class: org.conscrypt.ConscryptHostnameVerifier
2020-11-21T12:33:28.0883320Z 
2020-11-21T12:33:28.1477319Z > Task :app:kaptGenerateStubsProprietaryReleaseKotlin
2020-11-21T12:33:28.1522805Z > Task :app:shrinkLibreReleaseRes
2020-11-21T12:33:31.4537465Z > Task :app:packageLibreRelease
2020-11-21T12:33:31.4538284Z > Task :app:assembleLibreRelease
2020-11-21T12:33:31.4540520Z > Task :app:javaPreCompileProprietaryRelease
2020-11-21T12:33:31.4549955Z > Task :app:mergeProprietaryReleaseNativeDebugMetadata NO-SOURCE
2020-11-21T12:33:31.4552089Z > Task :app:mergeProprietaryReleaseShaders
2020-11-21T12:33:31.4552668Z > Task :app:compileProprietaryReleaseShaders NO-SOURCE
2020-11-21T12:33:31.4553195Z > Task :app:generateProprietaryReleaseAssets UP-TO-DATE
2020-11-21T12:33:31.5521500Z > Task :app:mergeProprietaryReleaseAssets
2020-11-21T12:33:31.5523093Z > Task :app:compressProprietaryReleaseAssets
2020-11-21T12:33:31.6526995Z > Task :app:checkProprietaryReleaseDuplicateClasses
2020-11-21T12:33:32.0524927Z > Task :app:processProprietaryReleaseJavaRes NO-SOURCE
2020-11-21T12:33:33.4588946Z > Task :app:collectProprietaryReleaseDependencies
2020-11-21T12:33:33.4590803Z > Task :app:sdkProprietaryReleaseDependencyData
2020-11-21T12:33:33.4591413Z > Task :app:mergeProprietaryReleaseJniLibFolders
2020-11-21T12:33:35.2521586Z > Task :app:mergeProprietaryReleaseNativeLibs
2020-11-21T12:33:35.2524330Z > Task :app:stripProprietaryReleaseDebugSymbols NO-SOURCE
2020-11-21T12:33:36.6520736Z 
2020-11-21T12:33:36.6522225Z > Task :app:kaptProprietaryReleaseKotlin
2020-11-21T12:33:36.9583363Z warning: Current JDK version 11.0.9.1+1 has a bug (https://bugs.openjdk.java.net/browse/JDK-8007720) that prevents Room from being incremental. Consider using JDK 11+ or the embedded JDK shipped with Android Studio 3.5+.[WARN] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: androidx.room.RoomProcessor (DYNAMIC).
2020-11-21T12:33:51.3983861Z 
2020-11-21T12:33:51.3985966Z > Task :app:compileProprietaryReleaseKotlin
2020-11-21T12:33:51.4007724Z w: /home/vsts/work/1/s/app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt: (89, 30): Parameter 'target' is never used
2020-11-21T12:33:53.2521017Z 
2020-11-21T12:33:53.2522503Z > Task :app:compileProprietaryReleaseJavaWithJavac
2020-11-21T12:33:53.2523476Z 
2020-11-21T12:33:53.2524173Z > Task :app:compileProprietaryReleaseSources
2020-11-21T12:33:53.2569774Z Note: /home/vsts/work/1/s/app/src/proprietary/java/org/jellyfin/mobile/cast/ChromecastConnection.java uses or overrides a deprecated API.
2020-11-21T12:33:53.2571450Z Note: Recompile with -Xlint:deprecation for details.
2020-11-21T12:34:14.3521357Z > Task :app:lintVitalProprietaryRelease
2020-11-21T12:34:14.3523241Z > Task :app:mergeProprietaryReleaseGeneratedProguardFiles
2020-11-21T12:34:15.7521565Z > Task :app:mergeProprietaryReleaseJavaResource
2020-11-21T12:34:19.9520815Z 
2020-11-21T12:34:19.9522727Z > Task :app:minifyProprietaryReleaseWithR8
2020-11-21T12:34:19.9523494Z R8: Missing class: org.conscrypt.ConscryptHostnameVerifier
2020-11-21T12:36:45.1010730Z 
2020-11-21T12:36:45.1280528Z The message received from the daemon indicates that the daemon has disappeared.
2020-11-21T12:36:45.1533325Z Build request sent: Build{id=357f5c16-3415-400d-b3bc-6fce5ca91e59, currentDir=/home/vsts/work/1/s}
2020-11-21T12:36:45.1542955Z Attempting to read last messages from the daemon log...
2020-11-21T12:36:45.1549111Z Daemon pid: 2486
2020-11-21T12:36:45.1550748Z   log file: /home/vsts/.gradle/daemon/6.7/daemon-2486.out.log
2020-11-21T12:36:45.1552032Z ----- Last  20 lines from daemon log file - daemon-2486.out.log -----
2020-11-21T12:36:45.1552959Z warn: removing resource org.jellyfin.mobile:string/pref_enable_exoplayer_title without required default value.
2020-11-21T12:36:45.1560033Z 
2020-11-21T12:36:45.1564326Z warning: Current JDK version 11.0.9.1+1 has a bug (https://bugs.openjdk.java.net/browse/JDK-8007720) that prevents Room from being incremental. Consider using JDK 11+ or the embedded JDK shipped with Android Studio 3.5+.[WARN] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: androidx.room.RoomProcessor (DYNAMIC).
2020-11-21T12:36:45.1570634Z w: /home/vsts/work/1/s/app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt: (89, 30): Parameter 'target' is never used
2020-11-21T12:36:45.1571204Z warn: removing resource org.jellyfin.mobile:string/mediaservice_library_albums without required default value.
2020-11-21T12:36:45.1571740Z warn: removing resource org.jellyfin.mobile:string/mediaservice_library_artists without required default value.
2020-11-21T12:36:45.1575838Z warn: removing resource org.jellyfin.mobile:string/mediaservice_library_genres without required default value.
2020-11-21T12:36:45.1576457Z warn: removing resource org.jellyfin.mobile:string/mediaservice_library_latest without required default value.
2020-11-21T12:36:45.1577022Z warn: removing resource org.jellyfin.mobile:string/mediaservice_library_playlists without required default value.
2020-11-21T12:36:45.1577625Z warn: removing resource org.jellyfin.mobile:string/mediaservice_library_songs without required default value.
2020-11-21T12:36:45.1578206Z warn: removing resource org.jellyfin.mobile:string/mediaservice_shuffle without required default value.
2020-11-21T12:36:45.1579016Z warn: removing resource org.jellyfin.mobile:string/pref_enable_exoplayer_summary without required default value.
2020-11-21T12:36:45.1585236Z warn: removing resource org.jellyfin.mobile:string/pref_enable_exoplayer_title without required default value.
2020-11-21T12:36:45.1585917Z 
2020-11-21T12:36:45.1586539Z R8: Missing class: org.conscrypt.ConscryptHostnameVerifier
2020-11-21T12:36:45.1593248Z warning: Current JDK version 11.0.9.1+1 has a bug (https://bugs.openjdk.java.net/browse/JDK-8007720) that prevents Room from being incremental. Consider using JDK 11+ or the embedded JDK shipped with Android Studio 3.5+.[WARN] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: androidx.room.RoomProcessor (DYNAMIC).
2020-11-21T12:36:45.1600729Z w: /home/vsts/work/1/s/app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt: (89, 30): Parameter 'target' is never used
2020-11-21T12:36:45.1605438Z Note: /home/vsts/work/1/s/app/src/proprietary/java/org/jellyfin/mobile/cast/ChromecastConnection.java uses or overrides a deprecated API.
2020-11-21T12:36:45.1607777Z Note: Recompile with -Xlint:deprecation for details.
2020-11-21T12:36:45.1609611Z R8: Missing class: org.conscrypt.ConscryptHostnameVerifier
2020-11-21T12:36:45.1614131Z ----- End of the daemon log -----
2020-11-21T12:36:45.1615100Z 
2020-11-21T12:36:45.1615405Z 
2020-11-21T12:36:45.1615991Z FAILURE: Build failed with an exception.
2020-11-21T12:36:45.1616328Z 
2020-11-21T12:36:45.1811815Z * What went wrong:
2020-11-21T12:36:45.1812522Z Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
2020-11-21T12:36:45.1813042Z 
2020-11-21T12:36:45.1813314Z * Try:
2020-11-21T12:36:45.1814396Z Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
2020-11-21T12:36:45.1814984Z 
2020-11-21T12:36:45.1815331Z * Get more help at https://help.gradle.org
2020-11-21T12:36:45.2091607Z Error: The process '/home/vsts/work/1/s/gradlew' failed with exit code 1
2020-11-21T12:36:45.2092861Z     at ExecState._setResult (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-task-lib/toolrunner.js:816:25)
2020-11-21T12:36:45.2094154Z     at ExecState.CheckComplete (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-task-lib/toolrunner.js:799:18)
2020-11-21T12:36:45.2103213Z     at ChildProcess.<anonymous> (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-task-lib/toolrunner.js:721:19)
2020-11-21T12:36:45.2107375Z     at emitTwo (events.js:106:13)
2020-11-21T12:36:45.2110660Z     at ChildProcess.emit (events.js:191:7)
2020-11-21T12:36:45.2111718Z     at maybeClose (internal/child_process.js:920:16)
2020-11-21T12:36:45.2116310Z     at Socket.<anonymous> (internal/child_process.js:351:11)
2020-11-21T12:36:45.2117898Z     at emitOne (events.js:96:13)
2020-11-21T12:36:45.2118416Z     at Socket.emit (events.js:188:7)
2020-11-21T12:36:45.2118946Z     at Pipe._handle.close [as _onclose] (net.js:509:12)
2020-11-21T12:36:45.2406486Z ##[error]Error: The process '/home/vsts/work/1/s/gradlew' failed with exit code 1
2020-11-21T12:36:45.2799945Z ##[section]Finishing: Build Release
```
</details>

**Additional context**

Maybe it goes out of memory? I'm not sure.

**Comment by Maxr1998** [comment]
Should be fixed by moving to GitHub Actions. Closing in favor of #260.

**Comment by nielsvanvelzen** [comment]
oh cool

nice work
