### ISSUE TITLE
RuntimeException in MediaService if Play Services are missing

### ISSUE THREAD

**Issue by thgoebel** [jellyfin/jellyfin-android#304]
**Describe the bug**

On devices without Play Services, the `MediaService` crashes on every network change.

**To Reproduce**

1. Install Jellyfin Android on a device without Play Services
2. Log in, watch some movies
3. Close Jellyfin, reboot, get on with life
4. Change networks, e.g. from 4G to WiFi
5. Now the  `MediaService` seems to be fired, crashes, and Android greets you with the "Jellyfin keeps stopping" dialog.
 
The annoying thing here is, that you get A LOT of those "Jellyfin keeps stopping" popups as you move throughout the day (not actively using Jellyfin at all).

I don't have a device to cast to, so I don't know if casting works at all (maybe it crashes, too). That might be worth a separate issue, right now I'm most concerned about Jellyfin crashes interrupting my unrelated phone usage.

**Expected behavior**

Jellyfin should gracefully handle the absence of Play Services.

**Logs**
```
FATAL EXCEPTION: main
Process: org.jellyfin.mobile, PID: 18244

java.lang.RuntimeException: Unable to create service org.jellyfin.mobile.media.MediaService: java.lang.RuntimeException: com.google.android.gms.cast.framework.zzad: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3965)
	at android.app.ActivityThread.access$1500(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

Caused by: java.lang.RuntimeException: com.google.android.gms.cast.framework.zzad: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
	at j.b.a.c.c.s.b.c(com.google.android.gms:play-services-cast-framework@@19.0.0:10)
	at org.jellyfin.mobile.cast.CastPlayerProvider.<init>(CastPlayerProvider.kt:2)
	at org.jellyfin.mobile.media.MediaService$castPlayerProvider$2.invoke(MediaService.kt:1)
	at n.h.getValue(LazyJVM.kt:5)
	at org.jellyfin.mobile.media.MediaService.getCastPlayerProvider(Unknown Source:2)
	at org.jellyfin.mobile.media.MediaService.onCreate(MediaService.kt:66)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3953)
	... 8 more

Caused by: com.google.android.gms.cast.framework.zzad: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
	at j.b.a.c.h.b.h.a(com.google.android.gms:play-services-cast-framework@@19.0.0:10)
	at j.b.a.c.c.s.b.<init>(com.google.android.gms:play-services-cast-framework@@19.0.0:8)
	at j.b.a.c.c.s.b.c(com.google.android.gms:play-services-cast-framework@@19.0.0:9)
	... 14 more

Caused by: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
	at com.google.android.gms.dynamite.DynamiteModule.a(com.google.android.gms:play-services-basement@@17.1.0:27)
	at j.b.a.c.h.b.h.a(com.google.android.gms:play-services-cast-framework@@19.0.0:2)
	... 16 more
```

**Screenshots**

<img src=https://user-images.githubusercontent.com/33295590/108033706-b3146280-7034-11eb-99e1-3bf1e3bb505a.png width=400>

**System:**
 - App version: 2.2.3
 - Android version: Android 10, LineageOS 17.1 (no GApps - you guess it)
 - Device manufacturer and model: OnePlus 5 (cheeseburger)
 - Jellyfin server version: 10.6.4

 - The type of video player implementation used: integrated player (ExoPlayer) => thank you, the more native player is awesome!

**Additional context**
N/A

**Comment by nielsvanvelzen** [comment]
Are you using the libre or the proprietary edition of the app?

**Comment by thgoebel** [comment]
I got it from Google Play via Aurora Store, so I guess the proprietary one. I didn't see that there was a libre one in the releases, I'll try that.

**Comment by Maxr1998** [comment]
The libre release should work, but it still shouldn't crash in the propietary version. I'll look into fixing it, thanks for the report.
