### ISSUE TITLE
Theming Crash on startup (BUG)

### ISSUE THREAD

**Issue by samuel9554** [jellyfin/jellyfin-android#311]
Build from the repo will crash on startup on certains phone.

```
`2020-04-13 22:39:11.988 3869-3869/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-04-13 22:39:11.990 3869-3869/? E/Zygote: accessInfo : 1
2020-04-13 22:39:12.003 3869-3869/? I/jellyfin.mobil: Late-enabling -Xcheck:jni
2020-04-13 22:39:12.026 3869-3869/? E/jellyfin.mobil: Unknown bits set in runtime_flags: 0x8000
2020-04-13 22:39:12.128 3869-3869/? D/ActivityThread: setConscryptValidator
2020-04-13 22:39:12.128 3869-3869/? D/ActivityThread: setConscryptValidator - put
2020-04-13 22:39:12.180 3869-3869/org.jellyfin.mobile W/ActivityThread: Application org.jellyfin.mobile is waiting for the debugger on port 8100...
2020-04-13 22:39:12.212 3869-3869/org.jellyfin.mobile I/System.out: Sending WAIT chunk
2020-04-13 22:39:32.101 3869-3869/org.jellyfin.mobile I/System.out: Debugger has connected
2020-04-13 22:39:32.102 3869-3869/org.jellyfin.mobile I/System.out: waiting for debugger to settle...
2020-04-13 22:39:32.304 3869-3869/org.jellyfin.mobile I/chatty: uid=10429(org.jellyfin.mobile) identical 1 line
2020-04-13 22:39:32.506 3869-3869/org.jellyfin.mobile I/System.out: waiting for debugger to settle...
2020-04-13 22:39:32.708 3869-3869/org.jellyfin.mobile I/System.out: waiting for debugger to settle...
2020-04-13 22:39:32.910 3869-3869/org.jellyfin.mobile I/System.out: waiting for debugger to settle...
2020-04-13 22:39:33.116 3869-3869/org.jellyfin.mobile I/System.out: waiting for debugger to settle...
2020-04-13 22:39:33.318 3869-3869/org.jellyfin.mobile I/System.out: waiting for debugger to settle...
2020-04-13 22:39:33.520 3869-3869/org.jellyfin.mobile I/System.out: waiting for debugger to settle...
2020-04-13 22:39:33.722 3869-3869/org.jellyfin.mobile I/System.out: debugger has settled (1467)
2020-04-13 22:39:34.034 3869-3869/org.jellyfin.mobile I/CordovaLog: Changing log level to DEBUG(3)
2020-04-13 22:39:34.034 3869-3869/org.jellyfin.mobile I/CordovaActivity: Apache Cordova native platform version 8.1.0 is starting
2020-04-13 22:39:34.034 3869-3869/org.jellyfin.mobile D/CordovaActivity: CordovaActivity.onCreate()
2020-04-13 22:39:34.073 3869-3869/org.jellyfin.mobile I/WebViewFactory: Loading com.google.android.webview version 80.0.3987.162 (code 398716233)
2020-04-13 22:39:36.091 3869-3869/org.jellyfin.mobile I/cr_LibraryLoader: Loaded native library version number "80.0.3987.162"
2020-04-13 22:39:36.446 3869-3869/org.jellyfin.mobile D/ConnectivityManager: requestNetwork; CallingUid : 10429, CallingPid : 3869, PackageName : org.jellyfin.mobile
2020-04-13 22:39:36.453 3869-3869/org.jellyfin.mobile D/ConnectivityManager: requestNetwork; CallingUid : 10429, CallingPid : 3869, PackageName : org.jellyfin.mobile
2020-04-13 22:39:36.543 3869-3869/org.jellyfin.mobile I/MultiWindowDecorSupport: updateCaptionType >> DecorView@964691a[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
2020-04-13 22:39:36.543 3869-3869/org.jellyfin.mobile D/MultiWindowDecorSupport: setCaptionType = 0, DecorView = DecorView@964691a[]
2020-04-13 22:39:36.582 3869-3869/org.jellyfin.mobile D/SystemWebViewEngine: CordovaWebView is running on device made by: samsung
2020-04-13 22:39:36.593 3869-3869/org.jellyfin.mobile D/PluginManager: init()
2020-04-13 22:39:36.599 3869-3869/org.jellyfin.mobile D/Whitelist: Unlimited access to network resources
2020-04-13 22:39:36.603 3869-3869/org.jellyfin.mobile D/CordovaWebViewImpl: >>> loadUrl(file:///android_asset/www/index.html)
2020-04-13 22:39:36.620 3869-4607/org.jellyfin.mobile W/jellyfin.mobil: Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
2020-04-13 22:39:36.627 3869-4640/org.jellyfin.mobile I/AdrenoGLES: QUALCOMM build                   : 2b9feb8, I58d155b2d1
    Build Date                       : 12/04/19
    OpenGL ES Shader Compiler Version: EV031.27.05.01
    Local Branch                     : 
    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.8.3.R1.10.00.00.520.058
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
2020-04-13 22:39:36.627 3869-4640/org.jellyfin.mobile I/AdrenoGLES: Build Config                     : S P 8.0.11 AArch64
2020-04-13 22:39:37.134 3869-4640/org.jellyfin.mobile I/AdrenoGLES: PFP: 0x016ee187, ME: 0x00000000
2020-04-13 22:39:37.166 3869-3869/org.jellyfin.mobile D/CordovaActivity: Started the activity.
2020-04-13 22:39:37.170 3869-3869/org.jellyfin.mobile D/CordovaActivity: Resumed the activity.
2020-04-13 22:39:37.228 3869-3869/org.jellyfin.mobile D/ViewRootImpl@a04ee0f[MainActivity]: setView = com.android.internal.policy.DecorView@964691a TM=true MM=false
2020-04-13 22:39:37.244 3869-3869/org.jellyfin.mobile D/ConnectivityManager: requestNetwork; CallingUid : 10429, CallingPid : 3869, PackageName : org.jellyfin.mobile
2020-04-13 22:39:37.250 3869-3869/org.jellyfin.mobile D/ConnectivityManager: requestNetwork; CallingUid : 10429, CallingPid : 3869, PackageName : org.jellyfin.mobile
2020-04-13 22:39:37.269 3869-3869/org.jellyfin.mobile D/CordovaActivity: Paused the activity.
2020-04-13 22:39:37.276 3869-3869/org.jellyfin.mobile I/CordovaApp: Request to send event before messageChannel initialised: pause
2020-04-13 22:39:37.281 3869-3869/org.jellyfin.mobile D/ViewRootImpl@a04ee0f[MainActivity]: stopped(true) old=false
2020-04-13 22:39:37.281 3869-3869/org.jellyfin.mobile D/CordovaActivity: Stopped the activity.
2020-04-13 22:39:37.294 3869-3869/org.jellyfin.mobile D/ViewRootImpl@a04ee0f[MainActivity]: stopped(false) old=true
2020-04-13 22:39:37.295 3869-3869/org.jellyfin.mobile D/CordovaActivity: Started the activity.
2020-04-13 22:39:37.296 3869-3869/org.jellyfin.mobile D/ViewRootImpl@a04ee0f[MainActivity]: stopped(false) old=false
2020-04-13 22:39:37.297 3869-3869/org.jellyfin.mobile D/CordovaActivity: Resumed the activity.
2020-04-13 22:39:37.299 3869-3869/org.jellyfin.mobile I/CordovaApp: Request to send event before messageChannel initialised: resume
2020-04-13 22:39:37.343 3869-3869/org.jellyfin.mobile I/Choreographer: Skipped 42 frames!  The application may be doing too much work on its main thread.
2020-04-13 22:39:37.351 3869-3869/org.jellyfin.mobile V/InputMethodManager: Not IME target window, ignoring
2020-04-13 22:39:37.477 3869-3869/org.jellyfin.mobile D/ViewRootImpl@a04ee0f[MainActivity]: Relayout returned: old=(0,0,720,1480) new=(0,0,720,1480) req=(720,1480)0 dur=25 res=0x7 s={true 481614700544} ch=true
2020-04-13 22:39:37.479 3869-4483/org.jellyfin.mobile D/OpenGLRenderer: createReliableSurface : 0x70bcf9f480, 0x7022792000
2020-04-13 22:39:37.507 3869-4483/org.jellyfin.mobile W/Gralloc3: mapper 3.x is not supported
2020-04-13 22:39:37.648 3869-3869/org.jellyfin.mobile D/ViewRootImpl@a04ee0f[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
2020-04-13 22:39:37.648 3869-3869/org.jellyfin.mobile D/InputMethodManager: prepareNavigationBarInfo() DecorView@964691a[MainActivity]
2020-04-13 22:39:37.649 3869-3869/org.jellyfin.mobile D/InputMethodManager: getNavigationBarColor() -855310
2020-04-13 22:39:37.656 3869-3869/org.jellyfin.mobile D/InputMethodManager: prepareNavigationBarInfo() DecorView@964691a[MainActivity]
2020-04-13 22:39:37.656 3869-3869/org.jellyfin.mobile D/InputMethodManager: getNavigationBarColor() -855310
2020-04-13 22:39:37.656 3869-3869/org.jellyfin.mobile V/InputMethodManager: Starting input: tba=org.jellyfin.mobile ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
2020-04-13 22:39:37.657 3869-3869/org.jellyfin.mobile D/InputMethodManager: startInputInner - Id : 0
2020-04-13 22:39:37.657 3869-3869/org.jellyfin.mobile I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2020-04-13 22:39:37.725 3869-3869/org.jellyfin.mobile D/ViewRootImpl@a04ee0f[MainActivity]: MSG_RESIZED: frame=(0,0,720,1480) ci=(0,48,0,96) vi=(0,48,0,96) or=1
2020-04-13 22:39:37.728 3869-4640/org.jellyfin.mobile W/AudioCapabilities: Unsupported mime audio/x-ima
2020-04-13 22:39:37.730 3869-3869/org.jellyfin.mobile D/CordovaWebViewImpl: onPageDidNavigate(file:///android_asset/www/index.html)
2020-04-13 22:39:37.733 3869-3869/org.jellyfin.mobile D/InputMethodManager: prepareNavigationBarInfo() DecorView@964691a[MainActivity]
2020-04-13 22:39:37.733 3869-3869/org.jellyfin.mobile D/InputMethodManager: getNavigationBarColor() -855310
2020-04-13 22:39:37.733 3869-3869/org.jellyfin.mobile V/InputMethodManager: Starting input: tba=org.jellyfin.mobile ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
2020-04-13 22:39:37.734 3869-3869/org.jellyfin.mobile D/InputMethodManager: startInputInner - Id : 0
2020-04-13 22:39:37.734 3869-4640/org.jellyfin.mobile W/AudioCapabilities: Unsupported mime audio/x-ape
2020-04-13 22:39:37.742 3869-4640/org.jellyfin.mobile W/AudioCapabilities: Unsupported mime audio/mpeg-L1
2020-04-13 22:39:37.744 3869-4640/org.jellyfin.mobile W/AudioCapabilities: Unsupported mime audio/mpeg-L2
2020-04-13 22:39:37.746 3869-4640/org.jellyfin.mobile W/AudioCapabilities: Unsupported mime audio/x-ms-wma
2020-04-13 22:39:37.900 3869-4640/org.jellyfin.mobile W/VideoCapabilities: Unsupported mime video/mp43
2020-04-13 22:39:37.902 3869-4640/org.jellyfin.mobile W/VideoCapabilities: Unrecognized profile/level 1/32 for video/mp4v-es
2020-04-13 22:39:37.903 3869-4640/org.jellyfin.mobile W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
2020-04-13 22:39:37.903 3869-4640/org.jellyfin.mobile W/VideoCapabilities: Unrecognized profile/level 32768/64 for video/mp4v-es
2020-04-13 22:39:37.905 3869-4640/org.jellyfin.mobile W/VideoCapabilities: Unsupported mime video/wvc1
2020-04-13 22:39:37.909 3869-4640/org.jellyfin.mobile W/VideoCapabilities: Unsupported mime video/x-ms-wmv7
2020-04-13 22:39:37.911 3869-4640/org.jellyfin.mobile W/VideoCapabilities: Unsupported mime video/x-ms-wmv8
2020-04-13 22:39:38.334 3869-3869/org.jellyfin.mobile D/JsMessageQueue: Set native->JS mode to EvalBridgeMode
2020-04-13 22:39:38.555 3869-3869/org.jellyfin.mobile D/SystemWebChromeClient: file:///android_asset/www/index.html: Line 0 : Refused to load the image 'android-webview-video-poster:default_video_poster/-4876331137012843624' because it violates the following Content Security Policy directive: "default-src * 'self' 'unsafe-inline' 'unsafe-eval' blob: data: gap: file: filesystem: ws: wss:". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.
2020-04-13 22:39:38.555 3869-3869/org.jellyfin.mobile I/chromium: [INFO:CONSOLE(0)] "Refused to load the image 'android-webview-video-poster:default_video_poster/-4876331137012843624' because it violates the following Content Security Policy directive: "default-src * 'self' 'unsafe-inline' 'unsafe-eval' blob: data: gap: file: filesystem: ws: wss:". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.
    ", source: file:///android_asset/www/index.html (0)
2020-04-13 22:39:38.628 3869-3869/org.jellyfin.mobile D/SensorManager: registerListener :: 20, Game Rotation Vector  Non-wakeup, 16666, 0,  
2020-04-13 22:39:38.630 3869-3869/org.jellyfin.mobile D/SystemWebChromeClient: file:///android_asset/www/libraries/apiclient/connectionmanager.js?v=13: Line 461 : Begin ConnectionManager constructor
2020-04-13 22:39:38.630 3869-3869/org.jellyfin.mobile I/chromium: [INFO:CONSOLE(461)] "Begin ConnectionManager constructor", source: file:///android_asset/www/libraries/apiclient/connectionmanager.js?v=13 (461)
2020-04-13 22:39:38.632 3869-3869/org.jellyfin.mobile D/SystemWebChromeClient: file:///android_asset/www/scripts/site.js: Line 484 : initAfterDependencies promises resolved
2020-04-13 22:39:38.632 3869-3869/org.jellyfin.mobile I/chromium: [INFO:CONSOLE(484)] "initAfterDependencies promises resolved", source: file:///android_asset/www/scripts/site.js (484)
2020-04-13 22:39:38.663 3869-3869/org.jellyfin.mobile D/SensorManager: unregisterListener :: 20, Game Rotation Vector  Non-wakeup,  
2020-04-13 22:39:38.690 3869-3869/org.jellyfin.mobile D/Dialog: mIsSamsungBasicInteraction = false
2020-04-13 22:39:38.690 3869-3869/org.jellyfin.mobile D/Dialog: mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
2020-04-13 22:39:38.725 3869-3869/org.jellyfin.mobile D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2020-04-13 22:39:38.731 3869-3869/org.jellyfin.mobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.jellyfin.mobile, PID: 3869
    java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466)
        at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:94)
        at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
        at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:554)
        at android.app.Dialog.show(Dialog.java:394)
        at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1007)
        at org.jellyfin.mobile.NativeShell$1.run(NativeShell.java:80)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at `com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)`
```

**Comment by cromefire** [comment]
It seems to be related to the `AlertDialog` thing @dkanada noticed with my new dialog (but this time with the other dialog)

**Comment by dkanada** [comment]
This should be resolved now.
