### ISSUE TITLE
App force close on slow connection / low buffer, VolleyError

### ISSUE THREAD

**Issue by MagnificentMagician** [jellyfin/jellyfin-android#346]
There seems to be no error handler implemented. The app just immediately force closes upon low buffer. I doubt this is intended behaviour.

Jellyfin Android 2.2.3, Jellyfin Server 10.7.2, Android 10

Stack trace:
FATAL EXCEPTION: main
Process: org.jellyfin.mobile, PID: 30692
org.jellyfin.apiclient.model.net.HttpException: VolleyError com.android.volley.TimeoutError: 
	at j.a.b.e$b.run(ExecutorDelivery.java:12)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: com.android.volley.TimeoutError
	at j.a.b.o.b.f(BasicNetwork.java:37)
	at j.a.b.h.a(NetworkDispatcher.java:8)
	at j.a.b.h.run(NetworkDispatcher.java:2)

**Comment by Maxr1998** [comment]
Known issue, this is a bug with the current apiclient. Once we switched to the new SDK, such errors should be properly handled.

**Comment by MagnificentMagician** [comment]
Alright, thank you for the instant reply. Looking forward to watching uninterrupted with the new SDK.

**Comment by willymilkytron** [comment]
I've been waiting for a fix since Oct 2020 https://github.com/jellyfin/jellyfin-android/issues/164

**Comment by nielsvanvelzen** [comment]
We're working on the new SDK (#333) for the next version of the app.

**Comment by Maxr1998** [comment]
Those issues should be a thing of the past now. Please try 2.3.0-beta.3 from the releases (or Google Play when it's processed).
