### ISSUE TITLE
HTTP timeout causes crash when playing media

### ISSUE THREAD

**Issue by steelersfan7** [jellyfin/jellyfin-android#368]
**Describe the bug**
app crashed in main thread

**To Reproduce**
I started a movie and errored oout

**Expected behavior**
App should not crash

**Logs**
```
2021-05-06 23:46:57.549 19859-19859/org.jellyfin.mobile.debug E/RedScreenOfDeath: ══════════ Exception caught by Red Screen Of Death library ═════════
2021-05-06 23:46:57.549 19859-19859/org.jellyfin.mobile.debug E/RedScreenOfDeath: SocketTimeoutException
    io.ktor.network.sockets.SocketTimeoutException: Socket timeout has been expired [url=removed, socket_timeout=unknown] ms
        at io.ktor.client.features.HttpTimeoutKt.SocketTimeoutException(HttpTimeout.kt:209)
        at io.ktor.client.engine.okhttp.OkUtilsKt.mapOkHttpException(OkUtils.kt:75)
        at io.ktor.client.engine.okhttp.OkUtilsKt.access$mapOkHttpException(OkUtils.kt:1)
        at io.ktor.client.engine.okhttp.OkHttpCallback.onFailure(OkUtils.kt:38)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
        at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
        at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2021-05-06 23:46:57.549 19859-19859/org.jellyfin.mobile.debug E/RedScreenOfDeath: ════════════════════════════════════════════════════════════════════
```

**Screenshots**

**System (please complete the following information):**
 - App version: beta
 - Android version: [e.g. Android 11]
 - Device manufacturer and model: [galaxy note 20]
 - Jellyfin server version: [e.g. 10.7.5]
 - The type of video player implementation used: [web player (default), native player (ExoPlayer) or external player (mpv, VLC)]

Exoplayer internal
**Additional context**

**Comment by nielsvanvelzen** [comment]
Is this the same movie as #369? I need some more information to reproduce this.

**Comment by steelersfan7** [comment]
This was not the same movie, but trying the same movie today, results in it not crashing. Can probably close this issue out. I can't reproduce it myself.

**Comment by Maxr1998** [comment]
Still happens on the latest master, stack trace thanks to @CarlosOlivo:

```
2021-05-18 18:13:03.331 15144-15144/org.jellyfin.mobile.debug E/RedScreenOfDeath: ══════════ Exception caught by Red Screen Of Death library ═════════
2021-05-18 18:13:03.333 15144-15144/org.jellyfin.mobile.debug E/RedScreenOfDeath: SocketTimeoutException
    io.ktor.network.sockets.SocketTimeoutException: Socket timeout has expired [url=https://demo.jellyfin.org/stable/Sessions/Playing/Stopped, socket_timeout=unknown] ms
        at io.ktor.client.features.HttpTimeoutKt.SocketTimeoutException(HttpTimeout.kt:207)
        at io.ktor.client.engine.okhttp.OkUtilsKt.mapOkHttpException(OkUtils.kt:77)
```

Timeouts should be catched by the SDK, however, it only handles HttpTimeoutExceptions, not SocketTimeoutExceptions. Should be fixed in the SDK, thus marking as upstream.
