### ISSUE TITLE
Unsupported java.time breaks app on Android SDK < 26, should be desugared

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin-android#373]
**Describe the bug**

Importing `java.time.ZonedDateTime` on Android SDK < 26 won't work, RTFM https://developer.android.com/reference/java/time/ZonedDateTime

Either drop support for all Android < 8.0 devices, fix the Kotlin SDK or provide a ZonedDateTime shim

**To Reproduce**

1. Update app on Android device (version < 8.0)
2. Login
3. Try to play any video
4. "Unfortunately, Jellyfin has stopped"

**Expected behavior**

App not crashing. every. single. time.

**Logs**

```
05-10 18:32:05.261 1885-1885/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.jellyfin.mobile, PID: 1885
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZonedDateTime;
        at org.jellyfin.sdk.model.serializer.LocalDateTimeSerializer.deserialize(LocalDateTimeSerializer.kt:2)
        at org.jellyfin.sdk.model.serializer.LocalDateTimeSerializer.deserialize(LocalDateTimeSerializer.kt:1)
        at o.b.k.s.j.a(Polymorphic.kt:25)
        at o.b.k.s.l.x(StreamingJsonDecoder.kt:1)
        at o.b.k.s.l.l(StreamingJsonDecoder.kt:6)
        at j.a.a.a.a.C(outline)
        at org.jellyfin.sdk.model.api.UserItemDataDto$$serializer.deserialize(UserItemDataDto.kt:2)
        at org.jellyfin.sdk.model.api.UserItemDataDto$$serializer.deserialize(UserItemDataDto.kt:1)
        at o.b.k.s.j.a(Polymorphic.kt:25)
        at o.b.k.s.l.x(StreamingJsonDecoder.kt:1)
        at o.b.k.s.l.l(StreamingJsonDecoder.kt:6)
        at org.jellyfin.sdk.model.api.BaseItemDto$$serializer.deserialize(BaseItemDto.kt:2)
        at org.jellyfin.sdk.model.api.BaseItemDto$$serializer.deserialize(BaseItemDto.kt:1)
        at o.b.k.s.j.a(Polymorphic.kt:25)
        at o.b.k.s.l.x(StreamingJsonDecoder.kt:1)
        at o.b.k.s.l.B(StreamingJsonDecoder.kt:3)
        at l.a.a.f.x0(Unknown Source)
        at o.b.j.k0.h(CollectionSerializers.kt:1)
        at o.b.j.a.f(CollectionSerializers.kt:11)
        at o.b.j.a.deserialize(CollectionSerializers.kt:1)
        at o.b.k.s.j.a(Polymorphic.kt:25)
        at o.b.k.s.l.x(StreamingJsonDecoder.kt:1)
        at o.b.k.s.l.l(StreamingJsonDecoder.kt:6)
        at org.jellyfin.sdk.model.api.BaseItemDtoQueryResult$$serializer.deserialize(BaseItemDtoQueryResult.kt:2)
        at org.jellyfin.sdk.model.api.BaseItemDtoQueryResult$$serializer.deserialize(BaseItemDtoQueryResult.kt:1)
        at o.b.k.s.j.a(Polymorphic.kt:25)
        at o.b.k.s.l.x(StreamingJsonDecoder.kt:1)
        at o.b.k.a.a(Json.kt:3)
        at b.a.a.a.b.a.a.a(KotlinxSerializer.kt:11)
        at b.a.a.a.b.e.invokeSuspend(JsonFeature.kt:11)
        at b.a.a.a.b.e.e(JsonFeature.kt:2)
        at b.a.d.v.l.b(SuspendFunctionGun.kt:10)
        at b.a.d.v.l.v(SuspendFunctionGun.kt:16)
        at b.a.d.v.l.C(SuspendFunctionGun.kt:2)
        at b.a.a.a.j.invokeSuspend(HttpCallValidator.kt:4)
        at b.a.a.a.j.e(HttpCallValidator.kt:2)
        at b.a.d.v.l.b(SuspendFunctionGun.kt:10)
        at b.a.d.v.l.v(SuspendFunctionGun.kt:16)
        at b.a.d.v.l.a(SuspendFunctionGun.kt:5)
        at b.a.d.v.f.a(Pipeline.kt:38)
        at b.a.a.l.a.e(HttpClientCall.kt:17)
        at c.a.a.e.b.d.a(ItemsApi.kt:117)
        at c.a.a.e.b.d$b.invokeSuspend(ItemsApi.kt)
        at n.n.k.a.a.resumeWith(ContinuationImpl.kt:3)
        at b.a.d.v.l.c(SuspendFunctionGun.kt:11)
        at b.a.d.v.l.b(SuspendFunctionGun.kt:4)
        at b.a.d.v.l$a.resumeWith(SuspendFunctionGun.kt:5)
        at n.n.k.a.a.resumeWith(ContinuationImpl.kt:9)
        at b.a.d.v.l.c(SuspendFunctionGun.kt:11)
        at b.a.d.v.l.b(SuspendFunctionGun.kt:4)
        at b.a.d.v.l$a.resumeWith(SuspendFunctionGun.kt:5)
        at n.n.k.a.a.resumeWith(ContinuationImpl.kt:9)
        at b.a.d.v.l.c(SuspendFunctionGun.kt:11)
        at b.a.d.v.l.b(SuspendFunctionGun.kt:4)
        at b.a.d.v.l$a.resumeWith(SuspendFunctionGun.kt:5)
        at n.n.k.a.a.resumeWith(ContinuationImpl.kt:9)
        at b.a.d.v.l.c(SuspendFunctionGun.kt:11)
        at b.a.d.v.l.b(SuspendFunctionGun.kt:4)
        at b.a.d.v.l$a.resumeWith(SuspendFunctionGun.kt:5)
        at n.n.k.a.a.resumeWith(ContinuationImpl.kt:9)
        at o.a.l0.run(DispatchedTask.kt:18)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5763)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.ZonedDateTime" on path: DexPathList[[zip file "/data/app/org.jellyfin.mobile-2/base.apk"],nativeLibraryDirectories=[/data/app/org.jellyfin.mobile-2/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at org.jellyfin.sdk.model.serializer.LocalDateTimeSerializer.deserialize(LocalDateTimeSerializer.kt:2) 
        at org.jellyfin.sdk.model.serializer.LocalDateTimeSerializer.deserialize(LocalDateTimeSerializer.kt:1) 
        at o.b.k.s.j.a(Polymorphic.kt:25) 
        at o.b.k.s.l.x(StreamingJsonDecoder.kt:1) 
        at o.b.k.s.l.l(StreamingJsonDecoder.kt:6) 
        at j.a.a.a.a.C(outline) 
        at org.jellyfin.sdk.model.api.UserItemDataDto$$serializer.deserialize(UserItemDataDto.kt:2) 
        at org.jellyfin.sdk.model.api.UserItemDataDto$$serializer.deserialize(UserItemDataDto.kt:1) 
        at o.b.k.s.j.a(Polymorphic.kt:25) 
        at o.b.k.s.l.x(StreamingJsonDecoder.kt:1) 
        at o.b.k.s.l.l(StreamingJsonDecoder.kt:6) 
        at org.jellyfin.sdk.model.api.BaseItemDto$$serializer.deserialize(BaseItemDto.kt:2) 
        at org.jellyfin.sdk.model.api.BaseItemDto$$serializer.deserialize(BaseItemDto.kt:1) 
        at o.b.k.s.j.a(Polymorphic.kt:25) 
        at o.b.k.s.l.x(StreamingJsonDecoder.kt:1) 
        at o.b.k.s.l.B(StreamingJsonDecoder.kt:3) 
        at l.a.a.f.x0(Unknown Source) 
        at o.b.j.k0.h(CollectionSerializers.kt:1) 
        at o.b.j.a.f(CollectionSerializers.kt:11) 
        at o.b.j.a.deserialize(CollectionSerializers.kt:1) 
        at o.b.k.s.j.a(Polymorphic.kt:25) 
        at o.b.k.s.l.x(StreamingJsonDecoder.kt:1) 
        at o.b.k.s.l.l(StreamingJsonDecoder.kt:6) 
        at org.jellyfin.sdk.model.api.BaseItemDtoQueryResult$$serializer.deserialize(BaseItemDtoQueryResult.kt:2) 
        at org.jellyfin.sdk.model.api.BaseItemDtoQueryResult$$serializer.deserialize(BaseItemDtoQueryResult.kt:1) 
        at o.b.k.s.j.a(Polymorphic.kt:25) 
        at o.b.k.s.l.x(StreamingJsonDecoder.kt:1) 
        at o.b.k.a.a(Json.kt:3) 
        at b.a.a.a.b.a.a.a(KotlinxSerializer.kt:11) 
        at b.a.a.a.b.e.invokeSuspend(JsonFeature.kt:11) 
        at b.a.a.a.b.e.e(JsonFeature.kt:2) 
        at b.a.d.v.l.b(SuspendFunctionGun.kt:10) 
        at b.a.d.v.l.v(SuspendFunctionGun.kt:16) 
        at b.a.d.v.l.C(SuspendFunctionGun.kt:2) 
        at b.a.a.a.j.invokeSuspend(HttpCallValidator.kt:4) 
        at b.a.a.a.j.e(HttpCallValidator.kt:2) 
        at b.a.d.v.l.b(SuspendFunctionGun.kt:10) 
        at b.a.d.v.l.v(SuspendFunctionGun.kt:16) 
        at b.a.d.v.l.a(SuspendFunctionGun.kt:5) 
        at b.a.d.v.f.a(Pipeline.kt:38) 
        at b.a.a.l.a.e(HttpClientCall.kt:17) 
        at c.a.a.e.b.d.a(ItemsApi.kt:117) 
        at c.a.a.e.b.d$b.invokeSuspend(ItemsApi.kt) 
        at n.n.k.a.a.resumeWith(ContinuationImpl.kt:3) 
        at b.a.d.v.l.c(SuspendFunctionGun.kt:11) 
        at b.a.d.v.l.b(SuspendFunctionGun.kt:4) 
        at b.a.d.v.l$a.resumeWith(SuspendFunctionGun.kt:5) 
        at n.n.k.a.a.resumeWith(ContinuationImpl.kt:9) 
        at b.a.d.v.l.c(SuspendFunctionGun.kt:11) 
        at b.a.d.v.l.b(SuspendFunctionGun.kt:4) 
        at b.a.d.v.l$a.resumeWith(SuspendFunctionGun.kt:5) 
        at n.n.k.a.a.resumeWith(ContinuationImpl.kt:9) 
        at b.a.d.v.l.c(SuspendFunctionGun.kt:11) 
        at b.a.d.v.l.b(SuspendFunctionGun.kt:4) 
        at b.a.d.v.l$a.resumeWith(SuspendFunctionGun.kt:5) 
        at n.n.k.a.a.resumeWith(ContinuationImpl.kt:9) 
        at b.a.d.v.l.c(SuspendFunctionGun.kt:11) 
        at b.a.d.v.l.b(SuspendFunctionGun.kt:4) 
        at b.a.d.v.l$a.resumeWith(SuspendFunctionGun.kt:5) 
        at n.n.k.a.a.resumeWith(ContinuationImpl.kt:9) 
        at o.a.l0.run(DispatchedTask.kt:18) 
        at android.os.Handler.handleCallback(Handler.java:815) 
        at android.os.Handler.dispatchMessage(Handler.java:104) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:5763) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
    	Suppressed: java.lang.ClassNotFoundEx
```

**Screenshots**

**System (please complete the following information):**
 - App version: 2.3.0-beta.1
 - Android version: 7.0
 - Device manufacturer and model: Samsung Galaxy S7
 - Jellyfin server version: 10.7.0-1
 - The type of video player implementation used: ExoPlayer

**Additional context**

**Comment by willymilkytron** [comment]
I'm forced to uninstall Jellyfin completely from my devices because the old non-beta version won't let me login ("The server uses an unsupported version") and the new beta version can't even play a single video.

**Comment by nielsvanvelzen** [comment]
The current stable release supports 10.6 and up, the beta supports 10.7 and up. You said the server is running 10.7.0-1 (I recommend updating it due too security fixes btw) so it should work with the stable release. If video playback doesn't work at all in all player backends I recommend looking at your server config because it is probably borked.

**Comment by willymilkytron** [comment]
> You said the server is running 10.7.0-1 (I recommend updating it due too security fixes btw) so it should work with the stable release.

Well, it doesn't

>  If video playback doesn't work at all in all player backends I recommend looking at your server config because it is probably borked.

I updated the Android app today and it stopped working today, my server has been up and running for a couple of weeks (at the very least) and it's not the issue

> Learn some manners, first of all. You should notice that the tone of your bug report is completely inappropriate

How so?

**Comment by thornbill** [comment]
Please see the first point of our Code of Contact. https://jellyfin.org/docs/general/community-standards.html#code-of-conduct

Your language in this issue has been very confrontational and demanding.

**Comment by willymilkytron** [comment]
> Do exhibit kindness and empathy to others, and make them feel welcome.

Ehe, i'm not the host here so ... but i do feel welcome!

> Do not antagonize, flame, insult, demean, abuse, or harass others.

I did not. I did not demean (?) to fix this immediately, in fact i'm building a new .apk locally so i can use Jellyfin again! There was no flaming, insulting or abusing here.

> Do not use slurs or sexualized language. Do not dox or otherwise expose others' private information, even if it is shared publicly elsewhere.

... ok

**Comment by willymilkytron** [comment]
What i ask is to please please please test your code before pushing to into production, i'm not developer but i had to learn this stuff to be able to build and use Jellyfin on my phone ...

**Comment by nielsvanvelzen** [comment]
Feel free to fork and maintain it yourself then. I'm locking the issue for now because this discussion is not going anywhere.
