### ISSUE TITLE
App crashes trying to cast to Google Chromecast

### ISSUE THREAD

**Issue by exptom** [jellyfin/jellyfin-android#573]
### Describe the bug

Since the latest update (v2.4.1) Jellyfin app crashes whenever I try to cast.
* Select the cast button and choose the chromecast
* The jellyfin cast page loads on the TV
* As soon as you press play on any media item the app crashes.

Note this happens on both mine and my wifes phone (both on the same app version) and when trying to cast to both our chromecast ultra and chromecast v3

### Application version

2.4.1

### Where did you install the app from?

Google Play

### Device information

Google Pixel 4a

### Android version

Android 12

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by DWShuo** [comment]
I'm having the exact same issue. Everything is the same as above but im using a pixel 3a instead, and the chromecast device is the gen 3 version.

Here is the log from the server, it complains about slow HTTP Response from the jellyfin server to my pixel 3a with status code 200.
Then `WS "192.168.1.162" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."`, I'm guessing this is the part where the app crashed.

```
[2021-11-25 23:32:48.324 -08:00] [INF] WS "192.168.1.162" request
[2021-11-25 23:33:12.223 -08:00] [INF] GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 120000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 384000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "webm", AudioCodec: "vorbis,opus", VideoCodec: "vp8,vp9,av1", Type: Video }, DirectPlayProfile { Container: "mp4,m4v", AudioCodec: "aac,mp3,opus,flac,vorbis", VideoCodec: "h264,vp8,vp9,av1", Type: Video }, DirectPlayProfile { Container: "mov", AudioCodec: "aac,mp3,opus,flac,vorbis", VideoCodec: "h264", Type: Video }, DirectPlayProfile { Container: "opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "opus", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mp3", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "webma", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "ts", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "ts", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "webm", Type: Video, VideoCodec: "vpx", AudioCodec: "vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp4", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3,opus,flac,vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: VideoCodecTag, Value: "xvid", IsRequired: True }], ApplyConditions: [], Codec: null, Container: "avi" }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline", IsRequired: True }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "41", IsRequired: True }], ApplyConditions: [], Codec: "h264", Container: null }], ResponseProfiles: [ResponseProfile { Container: "m4v", AudioCodec: null, VideoCodec: null, Type: Video, OrgPn: null, MimeType: "video/mp4", Conditions: [] }], SubtitleProfiles: [SubtitleProfile { Format: "vtt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }] }
[2021-11-25 23:33:12.226 -08:00] [INF] User policy for "admin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2021-11-25 23:33:12.226 -08:00] [INF] Profile: "Unknown Profile", Path: "/mnt/raid/media/movies/video/video.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-11-25 23:33:12.226 -08:00] [INF] Profile: "Unknown Profile", No video direct play profiles found for "/mnt/raid/media/movies/video/video.mkv" with codec "h264"
[2021-11-25 23:33:12.228 -08:00] [INF] Profile: "Unknown Profile", Path: "/mnt/raid/media/movies/video/video.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-11-25 23:33:12.228 -08:00] [INF] Profile: "Unknown Profile", No video direct play profiles found for "/mnt/raid/media/movies/video/video.mkv" with codec "h264"
[2021-11-25 23:33:12.231 -08:00] [INF] Profile: "Unknown Profile", Path: "/mnt/raid/media/movies/video/video.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-11-25 23:33:12.231 -08:00] [INF] Profile: "Unknown Profile", No video direct play profiles found for "/mnt/raid/media/movies/video/video.mkv" with codec "h264"
[2021-11-25 23:33:12.799 -08:00] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -fflags +genpts -i file:"/mnt/raid/media/movies/video/video.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -start_at_zero -vsync -1 -codec:a:0 aac -ac 6 -ab 640000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/var/lib/jellyfin/transcodes/98efa25c0bb14f566e547571c98d17bd%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/98efa25c0bb14f566e547571c98d17bd.m3u8"
[2021-11-25 23:33:13.818 -08:00] [WRN] Slow HTTP Response from "http://192.168.1.100:8096/videos/d35acd37-717e-240f-b462-4af768043fd4/hls1/main/0.ts?DeviceId=6642d58668491f6e&MediaSourceId=d35acd37717e240fb4624af768043fd4&VideoCodec=h264&AudioCodec=aac,mp3&AudioStreamIndex=1&VideoBitrate=139360000&AudioBitrate=640000&PlaySessionId=b6c012c8611c487996b63d51e6944b9e&api_key=eaa07d579b75405e97c7e760e56c869a&SubtitleMethod=Encode&TranscodingMaxAudioChannels=6&RequireAvc=false&Tag=6cc2d3fc773171c9cb115144758fe75c&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=False&h264-profile=high,main,baseline,constrainedbaseline&h264-level=41&TranscodeReasons=VideoCodecNotSupported,AudioCodecNotSupported" to "192.168.1.162" in 0:00:01.0211082 with Status Code 200
[2021-11-25 23:33:24.234 -08:00] [WRN] WS "192.168.1.162" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2021-11-25 23:33:24.246 -08:00] [INF] WS "192.168.1.162" closed
[2021-11-25 23:33:42.278 -08:00] [INF] WS "192.168.1.162" request
```

**Comment by terinjokes** [comment]
Same issue from a Pixel 6 Pro to a Chromecast Ultra. Stacktrace from Android says:

```
java.lang.IllegalArgumentException: org.jellyfin.mobile: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```

This looks very similar to #559, so maybe there's a PendingIntent specific to Google Cast that was missed?

**Comment by jakobroehrl** [comment]
same issues here with Google Pixel 4a

**Comment by kade5** [comment]
I'm having the same issue on a pixel 5 with chromecast ultra and the app version 2.4.1. I tested it on version 2.4.0 and don't get this issue.

**Comment by schlnk** [comment]
Same issue on pixel 5a, android 12, app version 2.4.1.

Stack trace:
```11-28 23:44:37.207  7922  7922 E AndroidRuntime: FATAL EXCEPTION: main
11-28 23:44:37.207  7922  7922 E AndroidRuntime: Process: org.jellyfin.mobile, PID: 7922
11-28 23:44:37.207  7922  7922 E AndroidRuntime: java.lang.IllegalArgumentException: org.jellyfin.mobile: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
11-28 23:44:37.207  7922  7922 E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
11-28 23:44:37.207  7922  7922 E AndroidRuntime:        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
11-28 23:44:37.207  7922  7922 E AndroidRuntime:        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
11-28 23:44:37.207  7922  7922 E AndroidRuntime:        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
11-28 23:44:37.207  7922  7922 E AndroidRuntime:        at s4.k.g(com.google.android.gms:play-services-cast-framework@@20.0.0:14)
11-28 23:44:37.207  7922  7922 E AndroidRuntime:        at com.google.android.gms.cast.framework.b.q(com.google.android.gms:play-services-cast-framework@@20.0.0:8)
11-28 23:44:37.207  7922  7922 E AndroidRuntime:        at q4.e0.c(com.google.android.gms:play-services-cast-framework@@20.0.0:4)
11-28 23:44:37.207  7922  7922 E AndroidRuntime:        at l2.c.run(JobInfoSchedulerService.java:28)
11-28 23:44:37.207  7922  7922 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
11-28 23:44:37.207  7922  7922 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
11-28 23:44:37.207  7922  7922 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
11-28 23:44:37.207  7922  7922 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
11-28 23:44:37.207  7922  7922 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7838)
11-28 23:44:37.207  7922  7922 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-28 23:44:37.207  7922  7922 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-28 23:44:37.207  7922  7922 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)```

**Comment by TheHippo** [comment]
> This looks very similar to #559, so maybe there's a PendingIntent specific to Google Cast that was missed?

Looks similar but since #559 was published with 2.4.1 and didn't fixed the issue it must be something else.

**Comment by nielsvanvelzen** [comment]
I made a pull request (#577) with the changes suggested by @terinjokes (thanks!). If anyone experiencing this issue can verify this build fixes the issue we will release a new version:

https://github.com/jellyfin/jellyfin-android/suites/4502843534/artifacts/120192758 (from the pull request artifacts, sideload `jellyfin-android-v0.0.0-dev.1-proprietary-debug.apk` to your device)

**Comment by terinjokes** [comment]
Thanks for taking a look!

**Comment by Maxr1998** [comment]
> This looks very similar to #559, so maybe there's a PendingIntent specific to Google Cast that was missed?

Good catch, I only fixed that issue in the code of the app itself, but didn't check the libraries nor tested casting in the emulator.

**Comment by schlnk** [comment]
> I made a pull request (#577) with the changes suggested by @terinjokes (thanks!). If anyone experiencing this issue can verify this build fixes the issue we will release a new version:

Tried with debug version and can confirm that it works. Thanks for the quick fix!

**Comment by exptom** [comment]
Thank you everyone for debugging fixing this :tada: 
Do you have a rough ETA of when this fix might be included in a play store release?

**Comment by nielsvanvelzen** [comment]
The fix was published to the play store yesterday (almost 24 hours ago) and is still in review. It all depends on Google, sometimes the reviews take a day and sometimes they take a week. Not much to do about that from our side unfortunately.
