### ISSUE TITLE
add ability to go forward/backward video duration by dragging touch on screen

### ISSUE THREAD

**Issue by moeinrahimi** [jellyfin/jellyfin-android#77]
it would be really nice to have such a feature, mx player is an example that have this

**Comment by fagervan** [comment]
same problem.
server: jellyfin_10.3.1_windows-x64
client: android-beta9.
Log in the server:

[08:39:43] [INF] Deleting partial stream file(s) C:\jellyfin\transcode\transcoding-temp\28abad54e8a5ed1ca03d7f36c7a9d83a.mkv
[08:39:43] [ERR] Error deleting partial stream file(s) C:\jellyfin\transcode\transcoding-temp\28abad54e8a5ed1ca03d7f36c7a9d83a.mkv
System.IO.IOException: The process cannot access the file 'C:\jellyfin\transcode\transcoding-temp\28abad54e8a5ed1ca03d7f36c7a9d83a.mkv' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at MediaBrowser.Api.ApiEntryPoint.DeletePartialStreamFiles(String path, TranscodingJobType jobType, Int32 retryCount, Int32 delayMs)
