### ISSUE TITLE
App crash immediately after an attempt to launch it. 

### ISSUE THREAD

**Issue by V3semir** [jellyfin/jellyfin-android#794]
### Describe the bug

As in title. What I expect is the ability to use this app. The same issue occurs in 3rd party apps as well. 

### Logs

```shell
Jellyfin Debug crashed in main thread
Version code: 2040499
Version name: 2.4.4
Stack Trace:
org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'org.jellyfin.mobile.MainViewModel']
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:60)
	at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:110)
	at org.koin.core.scope.Scope.resolveValue(Scope.kt:254)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
	at org.koin.core.scope.Scope.get(Scope.kt:204)
	at androidx.lifecycle.StateViewModelFactory.create(StateViewModelFactory.kt:17)
	at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:69)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:169)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:139)
	at org.koin.androidx.viewmodel.ViewModelResolverKt.resolveInstance(ViewModelResolver.kt:15)
	at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:67)
	at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:53)
	at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel$default(ScopeExt.kt:45)
	at org.koin.androidx.viewmodel.ext.android.ComponentCallbackExtKt.getViewModel(ComponentCallbackExt.kt:63)
	at org.jellyfin.mobile.MainActivity$special$$inlined$viewModel$default$2.invoke(ComponentCallbackExt.kt:65)
	at org.jellyfin.mobile.MainActivity$special$$inlined$viewModel$default$2.invoke(ComponentCallbackExt.kt:42)
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
	at org.jellyfin.mobile.MainActivity.getMainViewModel(MainActivity.kt:32)
	at org.jellyfin.mobile.MainActivity.access$getMainViewModel(MainActivity.kt:31)
	at org.jellyfin.mobile.MainActivity$onCreate$2.invokeSuspend(MainActivity.kt:80)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:75)
	at androidx.lifecycle.DispatchQueue.resume(DispatchQueue.kt:54)
	at androidx.lifecycle.LifecycleController$observer$1.onStateChanged(LifecycleController.kt:40)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
	at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.java:187)
	at android.app.Activity.dispatchActivityPostStarted(Activity.java:1420)
	at android.app.Activity.performStart(Activity.java:8352)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4060)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'org.jellyfin.mobile.app.ApiClientController']
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:60)
	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
	at org.koin.mp.KoinPlatformTools.synchronized(PlatformToolsJVM.kt:20)
	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:110)
	at org.koin.core.scope.Scope.resolveValue(Scope.kt:254)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
	at org.koin.core.scope.Scope.get(Scope.kt:204)
	at org.jellyfin.mobile.app.AppModuleKt$applicationModule$1$9.invoke(AppModule.kt:98)
	at org.jellyfin.mobile.app.AppModuleKt$applicationModule$1$9.invoke(AppModule.kt:54)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
	... 47 more
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'org.jellyfin.sdk.Jellyfin']
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:60)
	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
	at org.koin.mp.KoinPlatformTools.synchronized(PlatformToolsJVM.kt:20)
	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:110)
	at org.koin.core.scope.Scope.resolveValue(Scope.kt:254)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
	at org.koin.core.scope.Scope.get(Scope.kt:204)
	at org.jellyfin.mobile.app.AppModuleKt$applicationModule$1$8.invoke(AppModule.kt:98)
	at org.jellyfin.mobile.app.AppModuleKt$applicationModule$1$8.invoke(AppModule.kt:51)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
	... 59 more
Caused by: java.lang.NullPointerException: name must not be null
	at org.jellyfin.sdk.android.AndroidDeviceKt.androidDevice(AndroidDevice.kt:27)
	at org.jellyfin.sdk.JellyfinOptions$Builder.build(JellyfinOptions.kt:26)
	at org.jellyfin.mobile.app.ApiModuleKt$apiModule$1$1.invoke(ApiModule.kt:22)
	at org.jellyfin.mobile.app.ApiModuleKt$apiModule$1$1.invoke(ApiModule.kt:12)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
	... 71 more
```

### Application version

2.4.4

### Where did you install the app from?

Sideloaded APK (libre build)

### Device information

Samsung Galaxy S10+

### Android version

Android 12, One UI 4.1

### Jellyfin server version

10.8.4

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
It seems like your device doesn't have a name set, which should never happen. It looks like a bug in the system caused the name to be null - on my Samsung Android 12 device, the name was pre-filled and I cannot remove it.

You could try to open the system settings, navigate to "device info" or "phone info", and set a name.
Then, it'll hopefully launch again.

@nielsvanvelzen a fallback in the SDK if `Settings.Global.DEVICE_NAME` is null might still be a good idea.

**Comment by V3semir** [comment]
> It seems like your device doesn't have a name set, which should never happen. It looks like a bug in the system caused the name to be null - on my Samsung Android 12 device, the name was pre-filled and I cannot remove it.
> 
> You could try to open the system settings, navigate to "device info" or "phone info", and set a name. Then, it'll hopefully launch again.
> 
> @nielsvanvelzen a fallback in the SDK if `Settings.Global.DEVICE_NAME` is null might still be a good idea.

Thank you! That solved it!

**Comment by nielsvanvelzen** [comment]
Yeah it looks like the getString function in Settings.Global may return null so we should handle the null case. Never caught that one since there is no nullability annotation on the function.
